//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pirc.commerc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ИзмененияПакетаПредложений_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0418\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f\u041f\u0430\u043a\u0435\u0442\u0430\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439");
    private final static QName _Каталог_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041a\u0430\u0442\u0430\u043b\u043e\u0433");
    private final static QName _Классификатор_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440");
    private final static QName _ПакетПредложений_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041f\u0430\u043a\u0435\u0442\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439");
    private final static QName _Документ_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442");
    private final static QName _ПредставительПолноеНаименование_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041f\u043e\u043b\u043d\u043e\u0435\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435");
    private final static QName _ПредставительОбращение_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0435");
    private final static QName _ПредставительОКПО_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u041a\u041f\u041e");
    private final static QName _ПредставительКПП_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041a\u041f\u041f");
    private final static QName _ПредставительОКОПФ_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u041a\u041e\u041f\u0424");
    private final static QName _ПредставительФамилия_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0424\u0430\u043c\u0438\u043b\u0438\u044f");
    private final static QName _ПредставительИНН_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0418\u041d\u041d");
    private final static QName _ПредставительМестоРождения_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041c\u0435\u0441\u0442\u043e\u0420\u043e\u0436\u0434\u0435\u043d\u0438\u044f");
    private final static QName _ПредставительАдрес_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0410\u0434\u0440\u0435\u0441");
    private final static QName _ПредставительОКВЭД_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u041a\u0412\u042d\u0414");
    private final static QName _ПредставительДатаРегистрации_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0414\u0430\u0442\u0430\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438");
    private final static QName _ПредставительОтчество_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e");
    private final static QName _ПредставительКонтакты_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b");
    private final static QName _ПредставительОКДП_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u041a\u0414\u041f");
    private final static QName _ПредставительДолжность_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c");
    private final static QName _ПредставительУдостоверениеЛичности_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0423\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u0435\u043d\u0438\u0435\u041b\u0438\u0447\u043d\u043e\u0441\u0442\u0438");
    private final static QName _ПредставительИмя_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0418\u043c\u044f");
    private final static QName _ПредставительИд_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0418\u0434");
    private final static QName _ПредставительКомментарий_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439");
    private final static QName _ПредставительРасчетныеСчета_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0420\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0435\u0421\u0447\u0435\u0442\u0430");
    private final static QName _ПредставительОКФС_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u041a\u0424\u0421");
    private final static QName _ПредставительОфициальноеНаименование_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u0444\u0438\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0435\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435");
    private final static QName _ПредставительОрганизация_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f");
    private final static QName _ПредставительЕГРПО_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0415\u0413\u0420\u041f\u041e");
    private final static QName _ПредставительАдресРегистрации_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0410\u0434\u0440\u0435\u0441\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438");
    private final static QName _ПредставительПол_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041f\u043e\u043b");
    private final static QName _ПредставительРуководитель_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c");
    private final static QName _ПредставительДатаРождения_QNAME = new QName("urn:1C.ru:commerceml_2", "\u0414\u0430\u0442\u0430\u0420\u043e\u0436\u0434\u0435\u043d\u0438\u044f");
    private final static QName _ПредставительЮридическийАдрес_QNAME = new QName("urn:1C.ru:commerceml_2", "\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439\u0410\u0434\u0440\u0435\u0441");
    private final static QName _ПредставительНаименование_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435");
    private final static QName _ПредставительОтношение_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u0442\u043d\u043e\u0448\u0435\u043d\u0438\u0435");
    private final static QName _ПредставительОсновнойВидДеятельности_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439\u0412\u0438\u0434\u0414\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438");
    private final static QName _ТоварБазоваяЕдиницаПересчет_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041f\u0435\u0440\u0435\u0441\u0447\u0435\u0442");
    private final static QName _КонтрагентПредставители_QNAME = new QName("urn:1C.ru:commerceml_2", "\u041f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u0438");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pirc.commerc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Банк }
     * 
     */
    public Банк createБанк() {
        return new Банк();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Адрес }
     * 
     */
    public com.pirc.commerc.Адрес createАдрес() {
        return new com.pirc.commerc.Адрес();
    }

    /**
     * Create an instance of {@link Подписант }
     * 
     */
    public Подписант createПодписант() {
        return new Подписант();
    }

    /**
     * Create an instance of {@link Подписант.МестоРаботы }
     * 
     */
    public Подписант.МестоРаботы createПодписантМестоРаботы() {
        return new Подписант.МестоРаботы();
    }

    /**
     * Create an instance of {@link Представитель }
     * 
     */
    public Представитель createПредставитель() {
        return new Представитель();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент }
     * 
     */
    public ПодчиненныйДокумент createПодчиненныйДокумент() {
        return new ПодчиненныйДокумент();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары }
     * 
     */
    public ПодчиненныйДокумент.Товары createПодчиненныйДокументТовары() {
        return new ПодчиненныйДокумент.Товары();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар }
     * 
     */
    public com.pirc.commerc.Товар createТовар() {
        return new com.pirc.commerc.Товар();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары.Товар }
     * 
     */
    public ПодчиненныйДокумент.Товары.Товар createПодчиненныйДокументТоварыТовар() {
        return new ПодчиненныйДокумент.Товары.Товар();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары.Товар.Склады }
     * 
     */
    public ПодчиненныйДокумент.Товары.Товар.Склады createПодчиненныйДокументТоварыТоварСклады() {
        return new ПодчиненныйДокумент.Товары.Товар.Склады();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары.Товар.Скидки }
     * 
     */
    public ПодчиненныйДокумент.Товары.Товар.Скидки createПодчиненныйДокументТоварыТоварСкидки() {
        return new ПодчиненныйДокумент.Товары.Товар.Скидки();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары.Товар.Налоги }
     * 
     */
    public ПодчиненныйДокумент.Товары.Товар.Налоги createПодчиненныйДокументТоварыТоварНалоги() {
        return new ПодчиненныйДокумент.Товары.Товар.Налоги();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.Аналоги }
     * 
     */
    public com.pirc.commerc.Товар.Аналоги createТоварАналоги() {
        return new com.pirc.commerc.Товар.Аналоги();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.Комплектующие }
     * 
     */
    public com.pirc.commerc.Товар.Комплектующие createТоварКомплектующие() {
        return new com.pirc.commerc.Товар.Комплектующие();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.Акцизы }
     * 
     */
    public com.pirc.commerc.Товар.Акцизы createТоварАкцизы() {
        return new com.pirc.commerc.Товар.Акцизы();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.СтавкиНалогов }
     * 
     */
    public com.pirc.commerc.Товар.СтавкиНалогов createТоварСтавкиНалогов() {
        return new com.pirc.commerc.Товар.СтавкиНалогов();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.БазоваяЕдиница }
     * 
     */
    public com.pirc.commerc.Товар.БазоваяЕдиница createТоварБазоваяЕдиница() {
        return new com.pirc.commerc.Товар.БазоваяЕдиница();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Налоги }
     * 
     */
    public ПодчиненныйДокумент.Налоги createПодчиненныйДокументНалоги() {
        return new ПодчиненныйДокумент.Налоги();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Контрагенты }
     * 
     */
    public ПодчиненныйДокумент.Контрагенты createПодчиненныйДокументКонтрагенты() {
        return new ПодчиненныйДокумент.Контрагенты();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Контрагент }
     * 
     */
    public com.pirc.commerc.Контрагент createКонтрагент() {
        return new com.pirc.commerc.Контрагент();
    }

    /**
     * Create an instance of {@link ТипЦены }
     * 
     */
    public ТипЦены createТипЦены() {
        return new ТипЦены();
    }

    /**
     * Create an instance of {@link Руководитель }
     * 
     */
    public Руководитель createРуководитель() {
        return new Руководитель();
    }

    /**
     * Create an instance of {@link КонтактнаяИнформация }
     * 
     */
    public КонтактнаяИнформация createКонтактнаяИнформация() {
        return new КонтактнаяИнформация();
    }

    /**
     * Create an instance of {@link Свойство }
     * 
     */
    public Свойство createСвойство() {
        return new Свойство();
    }

    /**
     * Create an instance of {@link Свойство.ВариантыЗначений }
     * 
     */
    public Свойство.ВариантыЗначений createСвойствоВариантыЗначений() {
        return new Свойство.ВариантыЗначений();
    }

    /**
     * Create an instance of {@link Группа }
     * 
     */
    public Группа createГруппа() {
        return new Группа();
    }

    /**
     * Create an instance of {@link ХарактеристикиТовара }
     * 
     */
    public ХарактеристикиТовара createХарактеристикиТовара() {
        return new ХарактеристикиТовара();
    }

    /**
     * Create an instance of {@link ИзмененияПакетаПредложений }
     * 
     */
    public ИзмененияПакетаПредложений createИзмененияПакетаПредложений() {
        return new ИзмененияПакетаПредложений();
    }

    /**
     * Create an instance of {@link ИзмененияПакетаПредложений.Предложения }
     * 
     */
    public ИзмененияПакетаПредложений.Предложения createИзмененияПакетаПредложенийПредложения() {
        return new ИзмененияПакетаПредложений.Предложения();
    }

    /**
     * Create an instance of {@link ИзмененияПакетаПредложений.Предложения.Предложение }
     * 
     */
    public ИзмененияПакетаПредложений.Предложения.Предложение createИзмененияПакетаПредложенийПредложенияПредложение() {
        return new ИзмененияПакетаПредложений.Предложения.Предложение();
    }

    /**
     * Create an instance of {@link ПакетПредложений }
     * 
     */
    public ПакетПредложений createПакетПредложений() {
        return new ПакетПредложений();
    }

    /**
     * Create an instance of {@link ПакетПредложений.Предложения }
     * 
     */
    public ПакетПредложений.Предложения createПакетПредложенийПредложения() {
        return new ПакетПредложений.Предложения();
    }

    /**
     * Create an instance of {@link ПакетПредложений.Предложения.Предложение }
     * 
     */
    public ПакетПредложений.Предложения.Предложение createПакетПредложенийПредложенияПредложение() {
        return new ПакетПредложений.Предложения.Предложение();
    }

    /**
     * Create an instance of {@link Каталог }
     * 
     */
    public Каталог createКаталог() {
        return new Каталог();
    }

    /**
     * Create an instance of {@link Классификатор }
     * 
     */
    public Классификатор createКлассификатор() {
        return new Классификатор();
    }

    /**
     * Create an instance of {@link Документ }
     * 
     */
    public Документ createДокумент() {
        return new Документ();
    }

    /**
     * Create an instance of {@link Документ.Товары }
     * 
     */
    public Документ.Товары createДокументТовары() {
        return new Документ.Товары();
    }

    /**
     * Create an instance of {@link Документ.Товары.Товар }
     * 
     */
    public Документ.Товары.Товар createДокументТоварыТовар() {
        return new Документ.Товары.Товар();
    }

    /**
     * Create an instance of {@link Документ.Товары.Товар.Склады }
     * 
     */
    public Документ.Товары.Товар.Склады createДокументТоварыТоварСклады() {
        return new Документ.Товары.Товар.Склады();
    }

    /**
     * Create an instance of {@link Документ.Товары.Товар.Скидки }
     * 
     */
    public Документ.Товары.Товар.Скидки createДокументТоварыТоварСкидки() {
        return new Документ.Товары.Товар.Скидки();
    }

    /**
     * Create an instance of {@link Документ.Товары.Товар.Налоги }
     * 
     */
    public Документ.Товары.Товар.Налоги createДокументТоварыТоварНалоги() {
        return new Документ.Товары.Товар.Налоги();
    }

    /**
     * Create an instance of {@link Документ.Налоги }
     * 
     */
    public Документ.Налоги createДокументНалоги() {
        return new Документ.Налоги();
    }

    /**
     * Create an instance of {@link Документ.Контрагенты }
     * 
     */
    public Документ.Контрагенты createДокументКонтрагенты() {
        return new Документ.Контрагенты();
    }

    /**
     * Create an instance of {@link КоммерческаяИнформация }
     * 
     */
    public КоммерческаяИнформация createКоммерческаяИнформация() {
        return new КоммерческаяИнформация();
    }

    /**
     * Create an instance of {@link КоммерческаяИнформация1 }
     * 
     */
    public КоммерческаяИнформация1 createКоммерческаяИнформация1() {
        return new КоммерческаяИнформация1();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Склад }
     * 
     */
    public com.pirc.commerc.Склад createСклад() {
        return new com.pirc.commerc.Склад();
    }

    /**
     * Create an instance of {@link ДопРасход }
     * 
     */
    public ДопРасход createДопРасход() {
        return new ДопРасход();
    }

    /**
     * Create an instance of {@link ОстаткиПоСкладам }
     * 
     */
    public ОстаткиПоСкладам createОстаткиПоСкладам() {
        return new ОстаткиПоСкладам();
    }

    /**
     * Create an instance of {@link ЗначениеРеквизита }
     * 
     */
    public ЗначениеРеквизита createЗначениеРеквизита() {
        return new ЗначениеРеквизита();
    }

    /**
     * Create an instance of {@link Цена }
     * 
     */
    public Цена createЦена() {
        return new Цена();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Скидка }
     * 
     */
    public com.pirc.commerc.Скидка createСкидка() {
        return new com.pirc.commerc.Скидка();
    }

    /**
     * Create an instance of {@link РасчетныйСчет }
     * 
     */
    public РасчетныйСчет createРасчетныйСчет() {
        return new РасчетныйСчет();
    }

    /**
     * Create an instance of {@link ЗначенияСвойства }
     * 
     */
    public ЗначенияСвойства createЗначенияСвойства() {
        return new ЗначенияСвойства();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Налог }
     * 
     */
    public com.pirc.commerc.Налог createНалог() {
        return new com.pirc.commerc.Налог();
    }

    /**
     * Create an instance of {@link Банк.Адрес }
     * 
     */
    public Банк.Адрес createБанкАдрес() {
        return new Банк.Адрес();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Адрес.АдресноеПоле }
     * 
     */
    public com.pirc.commerc.Адрес.АдресноеПоле createАдресАдресноеПоле() {
        return new com.pirc.commerc.Адрес.АдресноеПоле();
    }

    /**
     * Create an instance of {@link Подписант.УдостоверениеЛичности }
     * 
     */
    public Подписант.УдостоверениеЛичности createПодписантУдостоверениеЛичности() {
        return new Подписант.УдостоверениеЛичности();
    }

    /**
     * Create an instance of {@link Подписант.МестоРаботы.РасчетныеСчета }
     * 
     */
    public Подписант.МестоРаботы.РасчетныеСчета createПодписантМестоРаботыРасчетныеСчета() {
        return new Подписант.МестоРаботы.РасчетныеСчета();
    }

    /**
     * Create an instance of {@link Представитель.УдостоверениеЛичности }
     * 
     */
    public Представитель.УдостоверениеЛичности createПредставительУдостоверениеЛичности() {
        return new Представитель.УдостоверениеЛичности();
    }

    /**
     * Create an instance of {@link Представитель.Организация }
     * 
     */
    public Представитель.Организация createПредставительОрганизация() {
        return new Представитель.Организация();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Скидки }
     * 
     */
    public ПодчиненныйДокумент.Скидки createПодчиненныйДокументСкидки() {
        return new ПодчиненныйДокумент.Скидки();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.ДопРасходы }
     * 
     */
    public ПодчиненныйДокумент.ДопРасходы createПодчиненныйДокументДопРасходы() {
        return new ПодчиненныйДокумент.ДопРасходы();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Склады }
     * 
     */
    public ПодчиненныйДокумент.Склады createПодчиненныйДокументСклады() {
        return new ПодчиненныйДокумент.Склады();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.ЗначенияРеквизитов }
     * 
     */
    public ПодчиненныйДокумент.ЗначенияРеквизитов createПодчиненныйДокументЗначенияРеквизитов() {
        return new ПодчиненныйДокумент.ЗначенияРеквизитов();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Подписанты }
     * 
     */
    public ПодчиненныйДокумент.Подписанты createПодчиненныйДокументПодписанты() {
        return new ПодчиненныйДокумент.Подписанты();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.Группы }
     * 
     */
    public com.pirc.commerc.Товар.Группы createТоварГруппы() {
        return new com.pirc.commerc.Товар.Группы();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.ЗначенияСвойств }
     * 
     */
    public com.pirc.commerc.Товар.ЗначенияСвойств createТоварЗначенияСвойств() {
        return new com.pirc.commerc.Товар.ЗначенияСвойств();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.ЗначенияРеквизитов }
     * 
     */
    public com.pirc.commerc.Товар.ЗначенияРеквизитов createТоварЗначенияРеквизитов() {
        return new com.pirc.commerc.Товар.ЗначенияРеквизитов();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные }
     * 
     */
    public ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные createПодчиненныйДокументТоварыТоварДополнительныеДанные() {
        return new ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары.Товар.ДопРасходы }
     * 
     */
    public ПодчиненныйДокумент.Товары.Товар.ДопРасходы createПодчиненныйДокументТоварыТоварДопРасходы() {
        return new ПодчиненныйДокумент.Товары.Товар.ДопРасходы();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары.Товар.ДополнительныеЗначенияРеквизитов }
     * 
     */
    public ПодчиненныйДокумент.Товары.Товар.ДополнительныеЗначенияРеквизитов createПодчиненныйДокументТоварыТоварДополнительныеЗначенияРеквизитов() {
        return new ПодчиненныйДокумент.Товары.Товар.ДополнительныеЗначенияРеквизитов();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары.Товар.Склады.Склад }
     * 
     */
    public ПодчиненныйДокумент.Товары.Товар.Склады.Склад createПодчиненныйДокументТоварыТоварСкладыСклад() {
        return new ПодчиненныйДокумент.Товары.Товар.Склады.Склад();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары.Товар.Скидки.Скидка }
     * 
     */
    public ПодчиненныйДокумент.Товары.Товар.Скидки.Скидка createПодчиненныйДокументТоварыТоварСкидкиСкидка() {
        return new ПодчиненныйДокумент.Товары.Товар.Скидки.Скидка();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Товары.Товар.Налоги.Налог }
     * 
     */
    public ПодчиненныйДокумент.Товары.Товар.Налоги.Налог createПодчиненныйДокументТоварыТоварНалогиНалог() {
        return new ПодчиненныйДокумент.Товары.Товар.Налоги.Налог();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.Аналоги.Аналог }
     * 
     */
    public com.pirc.commerc.Товар.Аналоги.Аналог createТоварАналогиАналог() {
        return new com.pirc.commerc.Товар.Аналоги.Аналог();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.Комплектующие.Комплектующее }
     * 
     */
    public com.pirc.commerc.Товар.Комплектующие.Комплектующее createТоварКомплектующиеКомплектующее() {
        return new com.pirc.commerc.Товар.Комплектующие.Комплектующее();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.Акцизы.Акциз }
     * 
     */
    public com.pirc.commerc.Товар.Акцизы.Акциз createТоварАкцизыАкциз() {
        return new com.pirc.commerc.Товар.Акцизы.Акциз();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.СтавкиНалогов.СтавкаНалога }
     * 
     */
    public com.pirc.commerc.Товар.СтавкиНалогов.СтавкаНалога createТоварСтавкиНалоговСтавкаНалога() {
        return new com.pirc.commerc.Товар.СтавкиНалогов.СтавкаНалога();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Товар.БазоваяЕдиница.Пересчет }
     * 
     */
    public com.pirc.commerc.Товар.БазоваяЕдиница.Пересчет createТоварБазоваяЕдиницаПересчет() {
        return new com.pirc.commerc.Товар.БазоваяЕдиница.Пересчет();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Налоги.Налог }
     * 
     */
    public ПодчиненныйДокумент.Налоги.Налог createПодчиненныйДокументНалогиНалог() {
        return new ПодчиненныйДокумент.Налоги.Налог();
    }

    /**
     * Create an instance of {@link ПодчиненныйДокумент.Контрагенты.Контрагент }
     * 
     */
    public ПодчиненныйДокумент.Контрагенты.Контрагент createПодчиненныйДокументКонтрагентыКонтрагент() {
        return new ПодчиненныйДокумент.Контрагенты.Контрагент();
    }

    /**
     * Create an instance of {@link com.pirc.commerc.Контрагент.Представители }
     * 
     */
    public com.pirc.commerc.Контрагент.Представители createКонтрагентПредставители() {
        return new com.pirc.commerc.Контрагент.Представители();
    }

    /**
     * Create an instance of {@link ТипЦены.Налог }
     * 
     */
    public ТипЦены.Налог createТипЦеныНалог() {
        return new ТипЦены.Налог();
    }

    /**
     * Create an instance of {@link Руководитель.УдостоверениеЛичности }
     * 
     */
    public Руководитель.УдостоверениеЛичности createРуководительУдостоверениеЛичности() {
        return new Руководитель.УдостоверениеЛичности();
    }

    /**
     * Create an instance of {@link КонтактнаяИнформация.Контакт }
     * 
     */
    public КонтактнаяИнформация.Контакт createКонтактнаяИнформацияКонтакт() {
        return new КонтактнаяИнформация.Контакт();
    }

    /**
     * Create an instance of {@link Свойство.ВариантыЗначений.Справочник }
     * 
     */
    public Свойство.ВариантыЗначений.Справочник createСвойствоВариантыЗначенийСправочник() {
        return new Свойство.ВариантыЗначений.Справочник();
    }

    /**
     * Create an instance of {@link Группа.Свойства }
     * 
     */
    public Группа.Свойства createГруппаСвойства() {
        return new Группа.Свойства();
    }

    /**
     * Create an instance of {@link Группа.Группы }
     * 
     */
    public Группа.Группы createГруппаГруппы() {
        return new Группа.Группы();
    }

    /**
     * Create an instance of {@link ХарактеристикиТовара.ХарактеристикаТовара }
     * 
     */
    public ХарактеристикиТовара.ХарактеристикаТовара createХарактеристикиТовараХарактеристикаТовара() {
        return new ХарактеристикиТовара.ХарактеристикаТовара();
    }

    /**
     * Create an instance of {@link ИзмененияПакетаПредложений.Предложения.Предложение.Цены }
     * 
     */
    public ИзмененияПакетаПредложений.Предложения.Предложение.Цены createИзмененияПакетаПредложенийПредложенияПредложениеЦены() {
        return new ИзмененияПакетаПредложений.Предложения.Предложение.Цены();
    }

    /**
     * Create an instance of {@link ПакетПредложений.ТипыЦен }
     * 
     */
    public ПакетПредложений.ТипыЦен createПакетПредложенийТипыЦен() {
        return new ПакетПредложений.ТипыЦен();
    }

    /**
     * Create an instance of {@link ПакетПредложений.Склады }
     * 
     */
    public ПакетПредложений.Склады createПакетПредложенийСклады() {
        return new ПакетПредложений.Склады();
    }

    /**
     * Create an instance of {@link ПакетПредложений.ЗначенияСвойств }
     * 
     */
    public ПакетПредложений.ЗначенияСвойств createПакетПредложенийЗначенияСвойств() {
        return new ПакетПредложений.ЗначенияСвойств();
    }

    /**
     * Create an instance of {@link ПакетПредложений.Подписанты }
     * 
     */
    public ПакетПредложений.Подписанты createПакетПредложенийПодписанты() {
        return new ПакетПредложений.Подписанты();
    }

    /**
     * Create an instance of {@link ПакетПредложений.Предложения.Предложение.Цены }
     * 
     */
    public ПакетПредложений.Предложения.Предложение.Цены createПакетПредложенийПредложенияПредложениеЦены() {
        return new ПакетПредложений.Предложения.Предложение.Цены();
    }

    /**
     * Create an instance of {@link Каталог.Товары }
     * 
     */
    public Каталог.Товары createКаталогТовары() {
        return new Каталог.Товары();
    }

    /**
     * Create an instance of {@link Каталог.Подписанты }
     * 
     */
    public Каталог.Подписанты createКаталогПодписанты() {
        return new Каталог.Подписанты();
    }

    /**
     * Create an instance of {@link Классификатор.Группы }
     * 
     */
    public Классификатор.Группы createКлассификаторГруппы() {
        return new Классификатор.Группы();
    }

    /**
     * Create an instance of {@link Классификатор.Свойства }
     * 
     */
    public Классификатор.Свойства createКлассификаторСвойства() {
        return new Классификатор.Свойства();
    }

    /**
     * Create an instance of {@link Классификатор.ТипыЦен }
     * 
     */
    public Классификатор.ТипыЦен createКлассификаторТипыЦен() {
        return new Классификатор.ТипыЦен();
    }

    /**
     * Create an instance of {@link Классификатор.Подписанты }
     * 
     */
    public Классификатор.Подписанты createКлассификаторПодписанты() {
        return new Классификатор.Подписанты();
    }

    /**
     * Create an instance of {@link Документ.Скидки }
     * 
     */
    public Документ.Скидки createДокументСкидки() {
        return new Документ.Скидки();
    }

    /**
     * Create an instance of {@link Документ.ДопРасходы }
     * 
     */
    public Документ.ДопРасходы createДокументДопРасходы() {
        return new Документ.ДопРасходы();
    }

    /**
     * Create an instance of {@link Документ.Склады }
     * 
     */
    public Документ.Склады createДокументСклады() {
        return new Документ.Склады();
    }

    /**
     * Create an instance of {@link Документ.ЗначенияРеквизитов }
     * 
     */
    public Документ.ЗначенияРеквизитов createДокументЗначенияРеквизитов() {
        return new Документ.ЗначенияРеквизитов();
    }

    /**
     * Create an instance of {@link Документ.Подписанты }
     * 
     */
    public Документ.Подписанты createДокументПодписанты() {
        return new Документ.Подписанты();
    }

    /**
     * Create an instance of {@link Документ.ПодчиненныеДокументы }
     * 
     */
    public Документ.ПодчиненныеДокументы createДокументПодчиненныеДокументы() {
        return new Документ.ПодчиненныеДокументы();
    }

    /**
     * Create an instance of {@link Документ.Товары.Товар.ДопРасходы }
     * 
     */
    public Документ.Товары.Товар.ДопРасходы createДокументТоварыТоварДопРасходы() {
        return new Документ.Товары.Товар.ДопРасходы();
    }

    /**
     * Create an instance of {@link Документ.Товары.Товар.ДополнительныеЗначенияРеквизитов }
     * 
     */
    public Документ.Товары.Товар.ДополнительныеЗначенияРеквизитов createДокументТоварыТоварДополнительныеЗначенияРеквизитов() {
        return new Документ.Товары.Товар.ДополнительныеЗначенияРеквизитов();
    }

    /**
     * Create an instance of {@link Документ.Товары.Товар.Склады.Склад }
     * 
     */
    public Документ.Товары.Товар.Склады.Склад createДокументТоварыТоварСкладыСклад() {
        return new Документ.Товары.Товар.Склады.Склад();
    }

    /**
     * Create an instance of {@link Документ.Товары.Товар.Скидки.Скидка }
     * 
     */
    public Документ.Товары.Товар.Скидки.Скидка createДокументТоварыТоварСкидкиСкидка() {
        return new Документ.Товары.Товар.Скидки.Скидка();
    }

    /**
     * Create an instance of {@link Документ.Товары.Товар.Налоги.Налог }
     * 
     */
    public Документ.Товары.Товар.Налоги.Налог createДокументТоварыТоварНалогиНалог() {
        return new Документ.Товары.Товар.Налоги.Налог();
    }

    /**
     * Create an instance of {@link Документ.Налоги.Налог }
     * 
     */
    public Документ.Налоги.Налог createДокументНалогиНалог() {
        return new Документ.Налоги.Налог();
    }

    /**
     * Create an instance of {@link Документ.Контрагенты.Контрагент }
     * 
     */
    public Документ.Контрагенты.Контрагент createДокументКонтрагентыКонтрагент() {
        return new Документ.Контрагенты.Контрагент();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ИзмененияПакетаПредложений }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0418\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f\u041f\u0430\u043a\u0435\u0442\u0430\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439")
    public JAXBElement<ИзмененияПакетаПредложений> createИзмененияПакетаПредложений(ИзмененияПакетаПредложений value) {
        return new JAXBElement<ИзмененияПакетаПредложений>(_ИзмененияПакетаПредложений_QNAME, ИзмененияПакетаПредложений.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Каталог }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041a\u0430\u0442\u0430\u043b\u043e\u0433")
    public JAXBElement<Каталог> createКаталог(Каталог value) {
        return new JAXBElement<Каталог>(_Каталог_QNAME, Каталог.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Классификатор }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440")
    public JAXBElement<Классификатор> createКлассификатор(Классификатор value) {
        return new JAXBElement<Классификатор>(_Классификатор_QNAME, Классификатор.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ПакетПредложений }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041f\u0430\u043a\u0435\u0442\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439")
    public JAXBElement<ПакетПредложений> createПакетПредложений(ПакетПредложений value) {
        return new JAXBElement<ПакетПредложений>(_ПакетПредложений_QNAME, ПакетПредложений.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Документ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442")
    public JAXBElement<Документ> createДокумент(Документ value) {
        return new JAXBElement<Документ>(_Документ_QNAME, Документ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041f\u043e\u043b\u043d\u043e\u0435\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", scope = Представитель.class)
    public JAXBElement<String> createПредставительПолноеНаименование(String value) {
        return new JAXBElement<String>(_ПредставительПолноеНаименование_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0435", scope = Представитель.class)
    public JAXBElement<String> createПредставительОбращение(String value) {
        return new JAXBElement<String>(_ПредставительОбращение_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u041a\u041f\u041e", scope = Представитель.class)
    public JAXBElement<String> createПредставительОКПО(String value) {
        return new JAXBElement<String>(_ПредставительОКПО_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041a\u041f\u041f", scope = Представитель.class)
    public JAXBElement<String> createПредставительКПП(String value) {
        return new JAXBElement<String>(_ПредставительКПП_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u041a\u041e\u041f\u0424", scope = Представитель.class)
    public JAXBElement<String> createПредставительОКОПФ(String value) {
        return new JAXBElement<String>(_ПредставительОКОПФ_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0424\u0430\u043c\u0438\u043b\u0438\u044f", scope = Представитель.class)
    public JAXBElement<String> createПредставительФамилия(String value) {
        return new JAXBElement<String>(_ПредставительФамилия_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0418\u041d\u041d", scope = Представитель.class)
    public JAXBElement<String> createПредставительИНН(String value) {
        return new JAXBElement<String>(_ПредставительИНН_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.pirc.commerc.Адрес }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041c\u0435\u0441\u0442\u043e\u0420\u043e\u0436\u0434\u0435\u043d\u0438\u044f", scope = Представитель.class)
    public JAXBElement<com.pirc.commerc.Адрес> createПредставительМестоРождения(com.pirc.commerc.Адрес value) {
        return new JAXBElement<com.pirc.commerc.Адрес>(_ПредставительМестоРождения_QNAME, com.pirc.commerc.Адрес.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.pirc.commerc.Адрес }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0410\u0434\u0440\u0435\u0441", scope = Представитель.class)
    public JAXBElement<com.pirc.commerc.Адрес> createПредставительАдрес(com.pirc.commerc.Адрес value) {
        return new JAXBElement<com.pirc.commerc.Адрес>(_ПредставительАдрес_QNAME, com.pirc.commerc.Адрес.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u041a\u0412\u042d\u0414", scope = Представитель.class)
    public JAXBElement<String> createПредставительОКВЭД(String value) {
        return new JAXBElement<String>(_ПредставительОКВЭД_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0414\u0430\u0442\u0430\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438", scope = Представитель.class)
    public JAXBElement<XMLGregorianCalendar> createПредставительДатаРегистрации(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ПредставительДатаРегистрации_QNAME, XMLGregorianCalendar.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e", scope = Представитель.class)
    public JAXBElement<String> createПредставительОтчество(String value) {
        return new JAXBElement<String>(_ПредставительОтчество_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link КонтактнаяИнформация }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b", scope = Представитель.class)
    public JAXBElement<КонтактнаяИнформация> createПредставительКонтакты(КонтактнаяИнформация value) {
        return new JAXBElement<КонтактнаяИнформация>(_ПредставительКонтакты_QNAME, КонтактнаяИнформация.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u041a\u0414\u041f", scope = Представитель.class)
    public JAXBElement<String> createПредставительОКДП(String value) {
        return new JAXBElement<String>(_ПредставительОКДП_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c", scope = Представитель.class)
    public JAXBElement<String> createПредставительДолжность(String value) {
        return new JAXBElement<String>(_ПредставительДолжность_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Представитель.УдостоверениеЛичности }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0423\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u0435\u043d\u0438\u0435\u041b\u0438\u0447\u043d\u043e\u0441\u0442\u0438", scope = Представитель.class)
    public JAXBElement<Представитель.УдостоверениеЛичности> createПредставительУдостоверениеЛичности(Представитель.УдостоверениеЛичности value) {
        return new JAXBElement<Представитель.УдостоверениеЛичности>(_ПредставительУдостоверениеЛичности_QNAME, Представитель.УдостоверениеЛичности.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0418\u043c\u044f", scope = Представитель.class)
    public JAXBElement<String> createПредставительИмя(String value) {
        return new JAXBElement<String>(_ПредставительИмя_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0418\u0434", scope = Представитель.class)
    public JAXBElement<String> createПредставительИд(String value) {
        return new JAXBElement<String>(_ПредставительИд_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439", scope = Представитель.class)
    public JAXBElement<String> createПредставительКомментарий(String value) {
        return new JAXBElement<String>(_ПредставительКомментарий_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Подписант.МестоРаботы.РасчетныеСчета }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0420\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0435\u0421\u0447\u0435\u0442\u0430", scope = Представитель.class)
    public JAXBElement<Подписант.МестоРаботы.РасчетныеСчета> createПредставительРасчетныеСчета(Подписант.МестоРаботы.РасчетныеСчета value) {
        return new JAXBElement<Подписант.МестоРаботы.РасчетныеСчета>(_ПредставительРасчетныеСчета_QNAME, Подписант.МестоРаботы.РасчетныеСчета.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u041a\u0424\u0421", scope = Представитель.class)
    public JAXBElement<String> createПредставительОКФС(String value) {
        return new JAXBElement<String>(_ПредставительОКФС_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0444\u0438\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0435\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", scope = Представитель.class)
    public JAXBElement<String> createПредставительОфициальноеНаименование(String value) {
        return new JAXBElement<String>(_ПредставительОфициальноеНаименование_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Представитель.Организация }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f", scope = Представитель.class)
    public JAXBElement<Представитель.Организация> createПредставительОрганизация(Представитель.Организация value) {
        return new JAXBElement<Представитель.Организация>(_ПредставительОрганизация_QNAME, Представитель.Организация.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0415\u0413\u0420\u041f\u041e", scope = Представитель.class)
    public JAXBElement<String> createПредставительЕГРПО(String value) {
        return new JAXBElement<String>(_ПредставительЕГРПО_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.pirc.commerc.Адрес }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0410\u0434\u0440\u0435\u0441\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438", scope = Представитель.class)
    public JAXBElement<com.pirc.commerc.Адрес> createПредставительАдресРегистрации(com.pirc.commerc.Адрес value) {
        return new JAXBElement<com.pirc.commerc.Адрес>(_ПредставительАдресРегистрации_QNAME, com.pirc.commerc.Адрес.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ПолТип }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041f\u043e\u043b", scope = Представитель.class)
    public JAXBElement<ПолТип> createПредставительПол(ПолТип value) {
        return new JAXBElement<ПолТип>(_ПредставительПол_QNAME, ПолТип.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Руководитель }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c", scope = Представитель.class)
    public JAXBElement<Руководитель> createПредставительРуководитель(Руководитель value) {
        return new JAXBElement<Руководитель>(_ПредставительРуководитель_QNAME, Руководитель.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0414\u0430\u0442\u0430\u0420\u043e\u0436\u0434\u0435\u043d\u0438\u044f", scope = Представитель.class)
    public JAXBElement<XMLGregorianCalendar> createПредставительДатаРождения(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ПредставительДатаРождения_QNAME, XMLGregorianCalendar.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.pirc.commerc.Адрес }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439\u0410\u0434\u0440\u0435\u0441", scope = Представитель.class)
    public JAXBElement<com.pirc.commerc.Адрес> createПредставительЮридическийАдрес(com.pirc.commerc.Адрес value) {
        return new JAXBElement<com.pirc.commerc.Адрес>(_ПредставительЮридическийАдрес_QNAME, com.pirc.commerc.Адрес.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", scope = Представитель.class)
    public JAXBElement<String> createПредставительНаименование(String value) {
        return new JAXBElement<String>(_ПредставительНаименование_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0442\u043d\u043e\u0448\u0435\u043d\u0438\u0435", scope = Представитель.class)
    public JAXBElement<String> createПредставительОтношение(String value) {
        return new JAXBElement<String>(_ПредставительОтношение_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439\u0412\u0438\u0434\u0414\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438", scope = Представитель.class)
    public JAXBElement<String> createПредставительОсновнойВидДеятельности(String value) {
        return new JAXBElement<String>(_ПредставительОсновнойВидДеятельности_QNAME, String.class, Представитель.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.pirc.commerc.Товар.БазоваяЕдиница.Пересчет }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041f\u0435\u0440\u0435\u0441\u0447\u0435\u0442", scope = com.pirc.commerc.Товар.БазоваяЕдиница.class)
    public JAXBElement<com.pirc.commerc.Товар.БазоваяЕдиница.Пересчет> createТоварБазоваяЕдиницаПересчет(com.pirc.commerc.Товар.БазоваяЕдиница.Пересчет value) {
        return new JAXBElement<com.pirc.commerc.Товар.БазоваяЕдиница.Пересчет>(_ТоварБазоваяЕдиницаПересчет_QNAME, com.pirc.commerc.Товар.БазоваяЕдиница.Пересчет.class, com.pirc.commerc.Товар.БазоваяЕдиница.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041f\u043e\u043b\u043d\u043e\u0435\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентПолноеНаименование(String value) {
        return new JAXBElement<String>(_ПредставительПолноеНаименование_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0435", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентОбращение(String value) {
        return new JAXBElement<String>(_ПредставительОбращение_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u041a\u041f\u041e", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентОКПО(String value) {
        return new JAXBElement<String>(_ПредставительОКПО_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041a\u041f\u041f", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентКПП(String value) {
        return new JAXBElement<String>(_ПредставительКПП_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u041a\u041e\u041f\u0424", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентОКОПФ(String value) {
        return new JAXBElement<String>(_ПредставительОКОПФ_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0424\u0430\u043c\u0438\u043b\u0438\u044f", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентФамилия(String value) {
        return new JAXBElement<String>(_ПредставительФамилия_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0418\u041d\u041d", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентИНН(String value) {
        return new JAXBElement<String>(_ПредставительИНН_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.pirc.commerc.Адрес }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041c\u0435\u0441\u0442\u043e\u0420\u043e\u0436\u0434\u0435\u043d\u0438\u044f", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<com.pirc.commerc.Адрес> createКонтрагентМестоРождения(com.pirc.commerc.Адрес value) {
        return new JAXBElement<com.pirc.commerc.Адрес>(_ПредставительМестоРождения_QNAME, com.pirc.commerc.Адрес.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.pirc.commerc.Адрес }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0410\u0434\u0440\u0435\u0441", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<com.pirc.commerc.Адрес> createКонтрагентАдрес(com.pirc.commerc.Адрес value) {
        return new JAXBElement<com.pirc.commerc.Адрес>(_ПредставительАдрес_QNAME, com.pirc.commerc.Адрес.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u041a\u0412\u042d\u0414", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентОКВЭД(String value) {
        return new JAXBElement<String>(_ПредставительОКВЭД_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0414\u0430\u0442\u0430\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<XMLGregorianCalendar> createКонтрагентДатаРегистрации(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ПредставительДатаРегистрации_QNAME, XMLGregorianCalendar.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентОтчество(String value) {
        return new JAXBElement<String>(_ПредставительОтчество_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link КонтактнаяИнформация }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<КонтактнаяИнформация> createКонтрагентКонтакты(КонтактнаяИнформация value) {
        return new JAXBElement<КонтактнаяИнформация>(_ПредставительКонтакты_QNAME, КонтактнаяИнформация.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u041a\u0414\u041f", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентОКДП(String value) {
        return new JAXBElement<String>(_ПредставительОКДП_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентДолжность(String value) {
        return new JAXBElement<String>(_ПредставительДолжность_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Представитель.УдостоверениеЛичности }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0423\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u0435\u043d\u0438\u0435\u041b\u0438\u0447\u043d\u043e\u0441\u0442\u0438", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<Представитель.УдостоверениеЛичности> createКонтрагентУдостоверениеЛичности(Представитель.УдостоверениеЛичности value) {
        return new JAXBElement<Представитель.УдостоверениеЛичности>(_ПредставительУдостоверениеЛичности_QNAME, Представитель.УдостоверениеЛичности.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0418\u043c\u044f", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентИмя(String value) {
        return new JAXBElement<String>(_ПредставительИмя_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0418\u0434", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентИд(String value) {
        return new JAXBElement<String>(_ПредставительИд_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентКомментарий(String value) {
        return new JAXBElement<String>(_ПредставительКомментарий_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Подписант.МестоРаботы.РасчетныеСчета }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0420\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0435\u0421\u0447\u0435\u0442\u0430", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<Подписант.МестоРаботы.РасчетныеСчета> createКонтрагентРасчетныеСчета(Подписант.МестоРаботы.РасчетныеСчета value) {
        return new JAXBElement<Подписант.МестоРаботы.РасчетныеСчета>(_ПредставительРасчетныеСчета_QNAME, Подписант.МестоРаботы.РасчетныеСчета.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u041a\u0424\u0421", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентОКФС(String value) {
        return new JAXBElement<String>(_ПредставительОКФС_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0444\u0438\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0435\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентОфициальноеНаименование(String value) {
        return new JAXBElement<String>(_ПредставительОфициальноеНаименование_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Представитель.Организация }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<Представитель.Организация> createКонтрагентОрганизация(Представитель.Организация value) {
        return new JAXBElement<Представитель.Организация>(_ПредставительОрганизация_QNAME, Представитель.Организация.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0415\u0413\u0420\u041f\u041e", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентЕГРПО(String value) {
        return new JAXBElement<String>(_ПредставительЕГРПО_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.pirc.commerc.Адрес }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0410\u0434\u0440\u0435\u0441\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<com.pirc.commerc.Адрес> createКонтрагентАдресРегистрации(com.pirc.commerc.Адрес value) {
        return new JAXBElement<com.pirc.commerc.Адрес>(_ПредставительАдресРегистрации_QNAME, com.pirc.commerc.Адрес.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ПолТип }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041f\u043e\u043b", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<ПолТип> createКонтрагентПол(ПолТип value) {
        return new JAXBElement<ПолТип>(_ПредставительПол_QNAME, ПолТип.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Руководитель }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<Руководитель> createКонтрагентРуководитель(Руководитель value) {
        return new JAXBElement<Руководитель>(_ПредставительРуководитель_QNAME, Руководитель.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u0414\u0430\u0442\u0430\u0420\u043e\u0436\u0434\u0435\u043d\u0438\u044f", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<XMLGregorianCalendar> createКонтрагентДатаРождения(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ПредставительДатаРождения_QNAME, XMLGregorianCalendar.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.pirc.commerc.Адрес }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439\u0410\u0434\u0440\u0435\u0441", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<com.pirc.commerc.Адрес> createКонтрагентЮридическийАдрес(com.pirc.commerc.Адрес value) {
        return new JAXBElement<com.pirc.commerc.Адрес>(_ПредставительЮридическийАдрес_QNAME, com.pirc.commerc.Адрес.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентНаименование(String value) {
        return new JAXBElement<String>(_ПредставительНаименование_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439\u0412\u0438\u0434\u0414\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<String> createКонтрагентОсновнойВидДеятельности(String value) {
        return new JAXBElement<String>(_ПредставительОсновнойВидДеятельности_QNAME, String.class, com.pirc.commerc.Контрагент.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.pirc.commerc.Контрагент.Представители }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:1C.ru:commerceml_2", name = "\u041f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u0438", scope = com.pirc.commerc.Контрагент.class)
    public JAXBElement<com.pirc.commerc.Контрагент.Представители> createКонтрагентПредставители(com.pirc.commerc.Контрагент.Представители value) {
        return new JAXBElement<com.pirc.commerc.Контрагент.Представители>(_КонтрагентПредставители_QNAME, com.pirc.commerc.Контрагент.Представители.class, com.pirc.commerc.Контрагент.class, value);
    }

}
