//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for АдресТип.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="АдресТип">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Почтовый индекс"/>
 *     &lt;enumeration value="Страна"/>
 *     &lt;enumeration value="Регион"/>
 *     &lt;enumeration value="Район"/>
 *     &lt;enumeration value="Населенный пункт"/>
 *     &lt;enumeration value="Город"/>
 *     &lt;enumeration value="Улица"/>
 *     &lt;enumeration value="Дом"/>
 *     &lt;enumeration value="Корпус"/>
 *     &lt;enumeration value="Квартира"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "\u0410\u0434\u0440\u0435\u0441\u0422\u0438\u043f")
@XmlEnum
public enum АдресТип {

    @XmlEnumValue("\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0438\u043d\u0434\u0435\u043a\u0441")
    ПОЧТОВЫЙ_ИНДЕКС("\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0438\u043d\u0434\u0435\u043a\u0441"),
    @XmlEnumValue("\u0421\u0442\u0440\u0430\u043d\u0430")
    СТРАНА("\u0421\u0442\u0440\u0430\u043d\u0430"),
    @XmlEnumValue("\u0420\u0435\u0433\u0438\u043e\u043d")
    РЕГИОН("\u0420\u0435\u0433\u0438\u043e\u043d"),
    @XmlEnumValue("\u0420\u0430\u0439\u043e\u043d")
    РАЙОН("\u0420\u0430\u0439\u043e\u043d"),
    @XmlEnumValue("\u041d\u0430\u0441\u0435\u043b\u0435\u043d\u043d\u044b\u0439 \u043f\u0443\u043d\u043a\u0442")
    НАСЕЛЕННЫЙ_ПУНКТ("\u041d\u0430\u0441\u0435\u043b\u0435\u043d\u043d\u044b\u0439 \u043f\u0443\u043d\u043a\u0442"),
    @XmlEnumValue("\u0413\u043e\u0440\u043e\u0434")
    ГОРОД("\u0413\u043e\u0440\u043e\u0434"),
    @XmlEnumValue("\u0423\u043b\u0438\u0446\u0430")
    УЛИЦА("\u0423\u043b\u0438\u0446\u0430"),
    @XmlEnumValue("\u0414\u043e\u043c")
    ДОМ("\u0414\u043e\u043c"),
    @XmlEnumValue("\u041a\u043e\u0440\u043f\u0443\u0441")
    КОРПУС("\u041a\u043e\u0440\u043f\u0443\u0441"),
    @XmlEnumValue("\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430")
    КВАРТИРА("\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430");
    private final String value;

    АдресТип(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static АдресТип fromValue(String v) {
        for (АдресТип c: АдресТип.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
