//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Служит для представления адреса контрагента или любого другого участника бизнес-процесса
 * 
 * <p>Java class for Адрес complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Адрес">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Представление">
 *           &lt;simpleType>
 *             &lt;restriction base="{urn:1C.ru:commerceml_2}НаименованиеТип">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Комментарий" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{urn:1C.ru:commerceml_2}КомментарийТип">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="АдресноеПоле" maxOccurs="10" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Тип" type="{urn:1C.ru:commerceml_2}АдресТип"/>
 *                   &lt;element name="Значение" type="{urn:1C.ru:commerceml_2}СтрокаТип"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0410\u0434\u0440\u0435\u0441", propOrder = {
    "\u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0438\u0435",
    "\u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439",
    "\u0430\u0434\u0440\u0435\u0441\u043d\u043e\u0435\u041f\u043e\u043b\u0435"
})
@XmlSeeAlso({
    com.pirc.commerc.Банк.Адрес.class
})
public class Адрес {

    @XmlElement(name = "\u041f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0438\u0435", required = true)
    protected String представление;
    @XmlElement(name = "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439")
    protected String комментарий;
    @XmlElement(name = "\u0410\u0434\u0440\u0435\u0441\u043d\u043e\u0435\u041f\u043e\u043b\u0435")
    protected List<Адрес.АдресноеПоле> адресноеПоле;

    /**
     * Gets the value of the представление property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getПредставление() {
        return представление;
    }

    /**
     * Sets the value of the представление property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setПредставление(String value) {
        this.представление = value;
    }

    /**
     * Gets the value of the комментарий property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКомментарий() {
        return комментарий;
    }

    /**
     * Sets the value of the комментарий property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКомментарий(String value) {
        this.комментарий = value;
    }

    /**
     * Gets the value of the адресноеПоле property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the адресноеПоле property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getАдресноеПоле().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Адрес.АдресноеПоле }
     * 
     * 
     */
    public List<Адрес.АдресноеПоле> getАдресноеПоле() {
        if (адресноеПоле == null) {
            адресноеПоле = new ArrayList<Адрес.АдресноеПоле>();
        }
        return this.адресноеПоле;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Тип" type="{urn:1C.ru:commerceml_2}АдресТип"/>
     *         &lt;element name="Значение" type="{urn:1C.ru:commerceml_2}СтрокаТип"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0442\u0438\u043f",
        "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435"
    })
    public static class АдресноеПоле {

        @XmlElement(name = "\u0422\u0438\u043f", required = true)
        @XmlSchemaType(name = "string")
        protected АдресТип тип;
        @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435", required = true)
        protected String значение;

        /**
         * Gets the value of the тип property.
         * 
         * @return
         *     possible object is
         *     {@link АдресТип }
         *     
         */
        public АдресТип getТип() {
            return тип;
        }

        /**
         * Sets the value of the тип property.
         * 
         * @param value
         *     allowed object is
         *     {@link АдресТип }
         *     
         */
        public void setТип(АдресТип value) {
            this.тип = value;
        }

        /**
         * Gets the value of the значение property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getЗначение() {
            return значение;
        }

        /**
         * Sets the value of the значение property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setЗначение(String value) {
            this.значение = value;
        }

    }

}
