//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Служит для определения реквизитов КО или УБР (БИК, Наименование, Адрес и т.д.) через которые клиент осуществляет расчеты
 * 
 * <p>Java class for Банк complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Банк">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="СчетКорреспондентский" type="{urn:1C.ru:commerceml_2}СчетНомерТип" minOccurs="0"/>
 *         &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}НаименованиеТип" minOccurs="0"/>
 *         &lt;element name="Адрес" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:1C.ru:commerceml_2}Адрес">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Контакты" type="{urn:1C.ru:commerceml_2}КонтактнаяИнформация" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;choice>
 *             &lt;element name="БИК" type="{urn:1C.ru:commerceml_2}БИКТип"/>
 *             &lt;element name="SWIFT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0411\u0430\u043d\u043a", propOrder = {
    "\u0441\u0447\u0435\u0442\u041a\u043e\u0440\u0440\u0435\u0441\u043f\u043e\u043d\u0434\u0435\u043d\u0442\u0441\u043a\u0438\u0439",
    "\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435",
    "\u0430\u0434\u0440\u0435\u0441",
    "\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u044b",
    "\u0431\u0438\u043a",
    "swift"
})
public class Банк {

    @XmlElement(name = "\u0421\u0447\u0435\u0442\u041a\u043e\u0440\u0440\u0435\u0441\u043f\u043e\u043d\u0434\u0435\u043d\u0442\u0441\u043a\u0438\u0439")
    protected String счетКорреспондентский;
    @XmlElement(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435")
    protected String наименование;
    @XmlElement(name = "\u0410\u0434\u0440\u0435\u0441")
    protected Банк.Адрес адрес;
    @XmlElement(name = "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b")
    protected КонтактнаяИнформация контакты;
    @XmlElement(name = "\u0411\u0418\u041a")
    protected String бик;
    @XmlElement(name = "SWIFT")
    protected String swift;

    /**
     * Gets the value of the счетКорреспондентский property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getСчетКорреспондентский() {
        return счетКорреспондентский;
    }

    /**
     * Sets the value of the счетКорреспондентский property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setСчетКорреспондентский(String value) {
        this.счетКорреспондентский = value;
    }

    /**
     * Gets the value of the наименование property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНаименование() {
        return наименование;
    }

    /**
     * Sets the value of the наименование property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНаименование(String value) {
        this.наименование = value;
    }

    /**
     * Gets the value of the адрес property.
     * 
     * @return
     *     possible object is
     *     {@link Банк.Адрес }
     *     
     */
    public Банк.Адрес getАдрес() {
        return адрес;
    }

    /**
     * Sets the value of the адрес property.
     * 
     * @param value
     *     allowed object is
     *     {@link Банк.Адрес }
     *     
     */
    public void setАдрес(Банк.Адрес value) {
        this.адрес = value;
    }

    /**
     * Gets the value of the контакты property.
     * 
     * @return
     *     possible object is
     *     {@link КонтактнаяИнформация }
     *     
     */
    public КонтактнаяИнформация getКонтакты() {
        return контакты;
    }

    /**
     * Sets the value of the контакты property.
     * 
     * @param value
     *     allowed object is
     *     {@link КонтактнаяИнформация }
     *     
     */
    public void setКонтакты(КонтактнаяИнформация value) {
        this.контакты = value;
    }

    /**
     * Gets the value of the бик property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getБИК() {
        return бик;
    }

    /**
     * Sets the value of the бик property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setБИК(String value) {
        this.бик = value;
    }

    /**
     * Gets the value of the swift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWIFT() {
        return swift;
    }

    /**
     * Sets the value of the swift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWIFT(String value) {
        this.swift = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:1C.ru:commerceml_2}Адрес">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Адрес
        extends com.pirc.commerc.Адрес
    {


    }

}
