//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Описывает группу товаров в каталоге 
 * 
 * <p>Java class for Группа complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Группа">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ид" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип"/>
 *         &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}КомментарийТип"/>
 *         &lt;element name="Описание" type="{urn:1C.ru:commerceml_2}КомментарийТип" minOccurs="0"/>
 *         &lt;element name="Свойства" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Свойство" type="{urn:1C.ru:commerceml_2}Свойство" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Группы" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Группа" type="{urn:1C.ru:commerceml_2}Группа" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0413\u0440\u0443\u043f\u043f\u0430", propOrder = {
    "\u0438\u0434",
    "\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435",
    "\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435",
    "\u0441\u0432\u043e\u0439\u0441\u0442\u0432\u0430",
    "\u0433\u0440\u0443\u043f\u043f\u044b"
})
public class Группа {

    @XmlElement(name = "\u0418\u0434", required = true)
    protected String ид;
    @XmlElement(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", required = true)
    protected String наименование;
    @XmlElement(name = "\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435")
    protected String описание;
    @XmlElement(name = "\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430")
    protected Группа.Свойства свойства;
    @XmlElement(name = "\u0413\u0440\u0443\u043f\u043f\u044b")
    protected Группа.Группы группы;

    /**
     * Gets the value of the ид property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИд() {
        return ид;
    }

    /**
     * Sets the value of the ид property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИд(String value) {
        this.ид = value;
    }

    /**
     * Gets the value of the наименование property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНаименование() {
        return наименование;
    }

    /**
     * Sets the value of the наименование property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНаименование(String value) {
        this.наименование = value;
    }

    /**
     * Gets the value of the описание property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОписание() {
        return описание;
    }

    /**
     * Sets the value of the описание property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОписание(String value) {
        this.описание = value;
    }

    /**
     * Gets the value of the свойства property.
     * 
     * @return
     *     possible object is
     *     {@link Группа.Свойства }
     *     
     */
    public Группа.Свойства getСвойства() {
        return свойства;
    }

    /**
     * Sets the value of the свойства property.
     * 
     * @param value
     *     allowed object is
     *     {@link Группа.Свойства }
     *     
     */
    public void setСвойства(Группа.Свойства value) {
        this.свойства = value;
    }

    /**
     * Gets the value of the группы property.
     * 
     * @return
     *     possible object is
     *     {@link Группа.Группы }
     *     
     */
    public Группа.Группы getГруппы() {
        return группы;
    }

    /**
     * Sets the value of the группы property.
     * 
     * @param value
     *     allowed object is
     *     {@link Группа.Группы }
     *     
     */
    public void setГруппы(Группа.Группы value) {
        this.группы = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Группа" type="{urn:1C.ru:commerceml_2}Группа" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0433\u0440\u0443\u043f\u043f\u0430"
    })
    public static class Группы {

        @XmlElement(name = "\u0413\u0440\u0443\u043f\u043f\u0430", required = true)
        protected List<Группа> группа;

        /**
         * Gets the value of the группа property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the группа property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getГруппа().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Группа }
         * 
         * 
         */
        public List<Группа> getГруппа() {
            if (группа == null) {
                группа = new ArrayList<Группа>();
            }
            return this.группа;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Свойство" type="{urn:1C.ru:commerceml_2}Свойство" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0441\u0432\u043e\u0439\u0441\u0442\u0432\u043e"
    })
    public static class Свойства {

        @XmlElement(name = "\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u043e", required = true)
        protected List<Свойство> свойство;

        /**
         * Gets the value of the свойство property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the свойство property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getСвойство().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Свойство }
         * 
         * 
         */
        public List<Свойство> getСвойство() {
            if (свойство == null) {
                свойство = new ArrayList<Свойство>();
            }
            return this.свойство;
        }

    }

}
