//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Определяет хоз. операцию и реквизиты документа, а также роль предприятия в хоз операции
 * 
 * <p>Java class for Документ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Документ">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ид" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип"/>
 *         &lt;element name="Номер" type="{urn:1C.ru:commerceml_2}НомерТип"/>
 *         &lt;element name="Дата" type="{urn:1C.ru:commerceml_2}ДатаТип"/>
 *         &lt;element name="ХозОперация" type="{urn:1C.ru:commerceml_2}ХозОперацияТип"/>
 *         &lt;element name="Роль" type="{urn:1C.ru:commerceml_2}РольТип"/>
 *         &lt;element name="Валюта" type="{urn:1C.ru:commerceml_2}ВалютаТип"/>
 *         &lt;element name="Курс" type="{urn:1C.ru:commerceml_2}КоэффициентТип"/>
 *         &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
 *         &lt;element name="Контрагенты">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Контрагент" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{urn:1C.ru:commerceml_2}Контрагент">
 *                           &lt;sequence>
 *                             &lt;element name="Роль" type="{urn:1C.ru:commerceml_2}РольТип"/>
 *                             &lt;element name="РасчетныйСчет" type="{urn:1C.ru:commerceml_2}РасчетныйСчет" minOccurs="0"/>
 *                             &lt;element name="Склад" type="{urn:1C.ru:commerceml_2}Склад" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Время" type="{urn:1C.ru:commerceml_2}ВремяТип" minOccurs="0"/>
 *         &lt;element name="СрокПлатежа" type="{urn:1C.ru:commerceml_2}ДатаТип" minOccurs="0"/>
 *         &lt;element name="Комментарий" type="{urn:1C.ru:commerceml_2}КомментарийТип" minOccurs="0"/>
 *         &lt;element name="Налоги" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Налог" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{urn:1C.ru:commerceml_2}Налог">
 *                           &lt;sequence>
 *                             &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
 *                             &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Скидки" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Скидка" type="{urn:1C.ru:commerceml_2}Скидка" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ДопРасходы" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ДопРасход" type="{urn:1C.ru:commerceml_2}ДопРасход" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Склады" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Склад" type="{urn:1C.ru:commerceml_2}Склад" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Товары" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Товар" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
 *                           &lt;sequence>
 *                             &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *                             &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *                             &lt;element name="ЦенаЗаЕдиницу" type="{urn:1C.ru:commerceml_2}СуммаТип" minOccurs="0"/>
 *                             &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
 *                             &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип" minOccurs="0"/>
 *                             &lt;group ref="{urn:1C.ru:commerceml_2}ЕдиницаИзмерения" minOccurs="0"/>
 *                             &lt;element name="СтранаПроисхождения" type="{urn:1C.ru:commerceml_2}СтрокаТип" minOccurs="0"/>
 *                             &lt;element name="ГТД" type="{urn:1C.ru:commerceml_2}СтрокаТип" minOccurs="0"/>
 *                             &lt;element name="Налоги" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Налог" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{urn:1C.ru:commerceml_2}Налог">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
 *                                                 &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Скидки" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Скидка" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{urn:1C.ru:commerceml_2}Скидка">
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ДопРасходы" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ДопРасход" type="{urn:1C.ru:commerceml_2}ДопРасход" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ДополнительныеЗначенияРеквизитов" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ЗначениеРеквизита" type="{urn:1C.ru:commerceml_2}ЗначениеРеквизита" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Склады" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Склад" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{urn:1C.ru:commerceml_2}Склад">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ЗначенияРеквизитов" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ЗначениеРеквизита" type="{urn:1C.ru:commerceml_2}ЗначениеРеквизита" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Подписанты" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Подписант" type="{urn:1C.ru:commerceml_2}Подписант" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ПодчиненныеДокументы" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ПодчиненныйДокумент" type="{urn:1C.ru:commerceml_2}ПодчиненныйДокумент" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442", propOrder = {
    "\u0438\u0434",
    "\u043d\u043e\u043c\u0435\u0440",
    "\u0434\u0430\u0442\u0430",
    "\u0445\u043e\u0437\u041e\u043f\u0435\u0440\u0430\u0446\u0438\u044f",
    "\u0440\u043e\u043b\u044c",
    "\u0432\u0430\u043b\u044e\u0442\u0430",
    "\u043a\u0443\u0440\u0441",
    "\u0441\u0443\u043c\u043c\u0430",
    "\u043a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442\u044b",
    "\u0432\u0440\u0435\u043c\u044f",
    "\u0441\u0440\u043e\u043a\u041f\u043b\u0430\u0442\u0435\u0436\u0430",
    "\u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439",
    "\u043d\u0430\u043b\u043e\u0433\u0438",
    "\u0441\u043a\u0438\u0434\u043a\u0438",
    "\u0434\u043e\u043f\u0420\u0430\u0441\u0445\u043e\u0434\u044b",
    "\u0441\u043a\u043b\u0430\u0434\u044b",
    "\u0442\u043e\u0432\u0430\u0440\u044b",
    "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u043e\u0432",
    "\u043f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u044b",
    "\u043f\u043e\u0434\u0447\u0438\u043d\u0435\u043d\u043d\u044b\u0435\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b"
})
public class Документ {

    @XmlElement(name = "\u0418\u0434", required = true)
    protected String ид;
    @XmlElement(name = "\u041d\u043e\u043c\u0435\u0440", required = true)
    protected String номер;
    @XmlElement(name = "\u0414\u0430\u0442\u0430", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar дата;
    @XmlElement(name = "\u0425\u043e\u0437\u041e\u043f\u0435\u0440\u0430\u0446\u0438\u044f", required = true)
    @XmlSchemaType(name = "string")
    protected ХозОперацияТип хозОперация;
    @XmlElement(name = "\u0420\u043e\u043b\u044c", required = true)
    @XmlSchemaType(name = "string")
    protected РольТип роль;
    @XmlElement(name = "\u0412\u0430\u043b\u044e\u0442\u0430", required = true)
    protected String валюта;
    @XmlElement(name = "\u041a\u0443\u0440\u0441", required = true)
    protected String курс;
    @XmlElement(name = "\u0421\u0443\u043c\u043c\u0430", required = true)
    protected BigDecimal сумма;
    @XmlElement(name = "\u041a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442\u044b", required = true)
    protected Документ.Контрагенты контрагенты;
    @XmlElement(name = "\u0412\u0440\u0435\u043c\u044f")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar время;
    @XmlElement(name = "\u0421\u0440\u043e\u043a\u041f\u043b\u0430\u0442\u0435\u0436\u0430")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar срокПлатежа;
    @XmlElement(name = "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439")
    protected String комментарий;
    @XmlElement(name = "\u041d\u0430\u043b\u043e\u0433\u0438")
    protected Документ.Налоги налоги;
    @XmlElement(name = "\u0421\u043a\u0438\u0434\u043a\u0438")
    protected Документ.Скидки скидки;
    @XmlElement(name = "\u0414\u043e\u043f\u0420\u0430\u0441\u0445\u043e\u0434\u044b")
    protected Документ.ДопРасходы допРасходы;
    @XmlElement(name = "\u0421\u043a\u043b\u0430\u0434\u044b")
    protected Документ.Склады склады;
    @XmlElement(name = "\u0422\u043e\u0432\u0430\u0440\u044b")
    protected Документ.Товары товары;
    @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u043e\u0432")
    protected Документ.ЗначенияРеквизитов значенияРеквизитов;
    @XmlElement(name = "\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u044b")
    protected Документ.Подписанты подписанты;
    @XmlElement(name = "\u041f\u043e\u0434\u0447\u0438\u043d\u0435\u043d\u043d\u044b\u0435\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b")
    protected Документ.ПодчиненныеДокументы подчиненныеДокументы;

    /**
     * Gets the value of the ид property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИд() {
        return ид;
    }

    /**
     * Sets the value of the ид property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИд(String value) {
        this.ид = value;
    }

    /**
     * Gets the value of the номер property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНомер() {
        return номер;
    }

    /**
     * Sets the value of the номер property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНомер(String value) {
        this.номер = value;
    }

    /**
     * Gets the value of the дата property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДата() {
        return дата;
    }

    /**
     * Sets the value of the дата property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДата(XMLGregorianCalendar value) {
        this.дата = value;
    }

    /**
     * Gets the value of the хозОперация property.
     * 
     * @return
     *     possible object is
     *     {@link ХозОперацияТип }
     *     
     */
    public ХозОперацияТип getХозОперация() {
        return хозОперация;
    }

    /**
     * Sets the value of the хозОперация property.
     * 
     * @param value
     *     allowed object is
     *     {@link ХозОперацияТип }
     *     
     */
    public void setХозОперация(ХозОперацияТип value) {
        this.хозОперация = value;
    }

    /**
     * Gets the value of the роль property.
     * 
     * @return
     *     possible object is
     *     {@link РольТип }
     *     
     */
    public РольТип getРоль() {
        return роль;
    }

    /**
     * Sets the value of the роль property.
     * 
     * @param value
     *     allowed object is
     *     {@link РольТип }
     *     
     */
    public void setРоль(РольТип value) {
        this.роль = value;
    }

    /**
     * Gets the value of the валюта property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getВалюта() {
        return валюта;
    }

    /**
     * Sets the value of the валюта property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setВалюта(String value) {
        this.валюта = value;
    }

    /**
     * Gets the value of the курс property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКурс() {
        return курс;
    }

    /**
     * Sets the value of the курс property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКурс(String value) {
        this.курс = value;
    }

    /**
     * Gets the value of the сумма property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getСумма() {
        return сумма;
    }

    /**
     * Sets the value of the сумма property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setСумма(BigDecimal value) {
        this.сумма = value;
    }

    /**
     * Gets the value of the контрагенты property.
     * 
     * @return
     *     possible object is
     *     {@link Документ.Контрагенты }
     *     
     */
    public Документ.Контрагенты getКонтрагенты() {
        return контрагенты;
    }

    /**
     * Sets the value of the контрагенты property.
     * 
     * @param value
     *     allowed object is
     *     {@link Документ.Контрагенты }
     *     
     */
    public void setКонтрагенты(Документ.Контрагенты value) {
        this.контрагенты = value;
    }

    /**
     * Gets the value of the время property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getВремя() {
        return время;
    }

    /**
     * Sets the value of the время property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setВремя(XMLGregorianCalendar value) {
        this.время = value;
    }

    /**
     * Gets the value of the срокПлатежа property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getСрокПлатежа() {
        return срокПлатежа;
    }

    /**
     * Sets the value of the срокПлатежа property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setСрокПлатежа(XMLGregorianCalendar value) {
        this.срокПлатежа = value;
    }

    /**
     * Gets the value of the комментарий property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКомментарий() {
        return комментарий;
    }

    /**
     * Sets the value of the комментарий property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКомментарий(String value) {
        this.комментарий = value;
    }

    /**
     * Gets the value of the налоги property.
     * 
     * @return
     *     possible object is
     *     {@link Документ.Налоги }
     *     
     */
    public Документ.Налоги getНалоги() {
        return налоги;
    }

    /**
     * Sets the value of the налоги property.
     * 
     * @param value
     *     allowed object is
     *     {@link Документ.Налоги }
     *     
     */
    public void setНалоги(Документ.Налоги value) {
        this.налоги = value;
    }

    /**
     * Gets the value of the скидки property.
     * 
     * @return
     *     possible object is
     *     {@link Документ.Скидки }
     *     
     */
    public Документ.Скидки getСкидки() {
        return скидки;
    }

    /**
     * Sets the value of the скидки property.
     * 
     * @param value
     *     allowed object is
     *     {@link Документ.Скидки }
     *     
     */
    public void setСкидки(Документ.Скидки value) {
        this.скидки = value;
    }

    /**
     * Gets the value of the допРасходы property.
     * 
     * @return
     *     possible object is
     *     {@link Документ.ДопРасходы }
     *     
     */
    public Документ.ДопРасходы getДопРасходы() {
        return допРасходы;
    }

    /**
     * Sets the value of the допРасходы property.
     * 
     * @param value
     *     allowed object is
     *     {@link Документ.ДопРасходы }
     *     
     */
    public void setДопРасходы(Документ.ДопРасходы value) {
        this.допРасходы = value;
    }

    /**
     * Gets the value of the склады property.
     * 
     * @return
     *     possible object is
     *     {@link Документ.Склады }
     *     
     */
    public Документ.Склады getСклады() {
        return склады;
    }

    /**
     * Sets the value of the склады property.
     * 
     * @param value
     *     allowed object is
     *     {@link Документ.Склады }
     *     
     */
    public void setСклады(Документ.Склады value) {
        this.склады = value;
    }

    /**
     * Gets the value of the товары property.
     * 
     * @return
     *     possible object is
     *     {@link Документ.Товары }
     *     
     */
    public Документ.Товары getТовары() {
        return товары;
    }

    /**
     * Sets the value of the товары property.
     * 
     * @param value
     *     allowed object is
     *     {@link Документ.Товары }
     *     
     */
    public void setТовары(Документ.Товары value) {
        this.товары = value;
    }

    /**
     * Gets the value of the значенияРеквизитов property.
     * 
     * @return
     *     possible object is
     *     {@link Документ.ЗначенияРеквизитов }
     *     
     */
    public Документ.ЗначенияРеквизитов getЗначенияРеквизитов() {
        return значенияРеквизитов;
    }

    /**
     * Sets the value of the значенияРеквизитов property.
     * 
     * @param value
     *     allowed object is
     *     {@link Документ.ЗначенияРеквизитов }
     *     
     */
    public void setЗначенияРеквизитов(Документ.ЗначенияРеквизитов value) {
        this.значенияРеквизитов = value;
    }

    /**
     * Gets the value of the подписанты property.
     * 
     * @return
     *     possible object is
     *     {@link Документ.Подписанты }
     *     
     */
    public Документ.Подписанты getПодписанты() {
        return подписанты;
    }

    /**
     * Sets the value of the подписанты property.
     * 
     * @param value
     *     allowed object is
     *     {@link Документ.Подписанты }
     *     
     */
    public void setПодписанты(Документ.Подписанты value) {
        this.подписанты = value;
    }

    /**
     * Gets the value of the подчиненныеДокументы property.
     * 
     * @return
     *     possible object is
     *     {@link Документ.ПодчиненныеДокументы }
     *     
     */
    public Документ.ПодчиненныеДокументы getПодчиненныеДокументы() {
        return подчиненныеДокументы;
    }

    /**
     * Sets the value of the подчиненныеДокументы property.
     * 
     * @param value
     *     allowed object is
     *     {@link Документ.ПодчиненныеДокументы }
     *     
     */
    public void setПодчиненныеДокументы(Документ.ПодчиненныеДокументы value) {
        this.подчиненныеДокументы = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ДопРасход" type="{urn:1C.ru:commerceml_2}ДопРасход" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0434\u043e\u043f\u0420\u0430\u0441\u0445\u043e\u0434"
    })
    public static class ДопРасходы {

        @XmlElement(name = "\u0414\u043e\u043f\u0420\u0430\u0441\u0445\u043e\u0434", required = true)
        protected List<ДопРасход> допРасход;

        /**
         * Gets the value of the допРасход property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the допРасход property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getДопРасход().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ДопРасход }
         * 
         * 
         */
        public List<ДопРасход> getДопРасход() {
            if (допРасход == null) {
                допРасход = new ArrayList<ДопРасход>();
            }
            return this.допРасход;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ЗначениеРеквизита" type="{urn:1C.ru:commerceml_2}ЗначениеРеквизита" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u0430"
    })
    public static class ЗначенияРеквизитов {

        @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u0430", required = true)
        protected List<ЗначениеРеквизита> значениеРеквизита;

        /**
         * Gets the value of the значениеРеквизита property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the значениеРеквизита property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getЗначениеРеквизита().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ЗначениеРеквизита }
         * 
         * 
         */
        public List<ЗначениеРеквизита> getЗначениеРеквизита() {
            if (значениеРеквизита == null) {
                значениеРеквизита = new ArrayList<ЗначениеРеквизита>();
            }
            return this.значениеРеквизита;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Контрагент" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{urn:1C.ru:commerceml_2}Контрагент">
     *                 &lt;sequence>
     *                   &lt;element name="Роль" type="{urn:1C.ru:commerceml_2}РольТип"/>
     *                   &lt;element name="РасчетныйСчет" type="{urn:1C.ru:commerceml_2}РасчетныйСчет" minOccurs="0"/>
     *                   &lt;element name="Склад" type="{urn:1C.ru:commerceml_2}Склад" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442"
    })
    public static class Контрагенты {

        @XmlElement(name = "\u041a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442", required = true)
        protected List<Документ.Контрагенты.Контрагент> контрагент;

        /**
         * Gets the value of the контрагент property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the контрагент property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getКонтрагент().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Документ.Контрагенты.Контрагент }
         * 
         * 
         */
        public List<Документ.Контрагенты.Контрагент> getКонтрагент() {
            if (контрагент == null) {
                контрагент = new ArrayList<Документ.Контрагенты.Контрагент>();
            }
            return this.контрагент;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{urn:1C.ru:commerceml_2}Контрагент">
         *       &lt;sequence>
         *         &lt;element name="Роль" type="{urn:1C.ru:commerceml_2}РольТип"/>
         *         &lt;element name="РасчетныйСчет" type="{urn:1C.ru:commerceml_2}РасчетныйСчет" minOccurs="0"/>
         *         &lt;element name="Склад" type="{urn:1C.ru:commerceml_2}Склад" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Контрагент
            extends com.pirc.commerc.Контрагент
        {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Налог" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{urn:1C.ru:commerceml_2}Налог">
     *                 &lt;sequence>
     *                   &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
     *                   &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043d\u0430\u043b\u043e\u0433"
    })
    public static class Налоги {

        @XmlElement(name = "\u041d\u0430\u043b\u043e\u0433", required = true)
        protected List<Документ.Налоги.Налог> налог;

        /**
         * Gets the value of the налог property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the налог property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getНалог().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Документ.Налоги.Налог }
         * 
         * 
         */
        public List<Документ.Налоги.Налог> getНалог() {
            if (налог == null) {
                налог = new ArrayList<Документ.Налоги.Налог>();
            }
            return this.налог;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{urn:1C.ru:commerceml_2}Налог">
         *       &lt;sequence>
         *         &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
         *         &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "\u0441\u0443\u043c\u043c\u0430",
            "\u0441\u0442\u0430\u0432\u043a\u0430"
        })
        public static class Налог
            extends com.pirc.commerc.Налог
        {

            @XmlElement(name = "\u0421\u0443\u043c\u043c\u0430", required = true)
            protected BigDecimal сумма;
            @XmlElement(name = "\u0421\u0442\u0430\u0432\u043a\u0430")
            protected String ставка;

            /**
             * Gets the value of the сумма property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getСумма() {
                return сумма;
            }

            /**
             * Sets the value of the сумма property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setСумма(BigDecimal value) {
                this.сумма = value;
            }

            /**
             * Gets the value of the ставка property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getСтавка() {
                return ставка;
            }

            /**
             * Sets the value of the ставка property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setСтавка(String value) {
                this.ставка = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Подписант" type="{urn:1C.ru:commerceml_2}Подписант" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442"
    })
    public static class Подписанты {

        @XmlElement(name = "\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442", required = true)
        protected List<Подписант> подписант;

        /**
         * Gets the value of the подписант property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the подписант property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getПодписант().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Подписант }
         * 
         * 
         */
        public List<Подписант> getПодписант() {
            if (подписант == null) {
                подписант = new ArrayList<Подписант>();
            }
            return this.подписант;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ПодчиненныйДокумент" type="{urn:1C.ru:commerceml_2}ПодчиненныйДокумент" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043f\u043e\u0434\u0447\u0438\u043d\u0435\u043d\u043d\u044b\u0439\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442"
    })
    public static class ПодчиненныеДокументы {

        @XmlElement(name = "\u041f\u043e\u0434\u0447\u0438\u043d\u0435\u043d\u043d\u044b\u0439\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442", required = true)
        protected List<ПодчиненныйДокумент> подчиненныйДокумент;

        /**
         * Gets the value of the подчиненныйДокумент property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the подчиненныйДокумент property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getПодчиненныйДокумент().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ПодчиненныйДокумент }
         * 
         * 
         */
        public List<ПодчиненныйДокумент> getПодчиненныйДокумент() {
            if (подчиненныйДокумент == null) {
                подчиненныйДокумент = new ArrayList<ПодчиненныйДокумент>();
            }
            return this.подчиненныйДокумент;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Скидка" type="{urn:1C.ru:commerceml_2}Скидка" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0441\u043a\u0438\u0434\u043a\u0430"
    })
    public static class Скидки {

        @XmlElement(name = "\u0421\u043a\u0438\u0434\u043a\u0430", required = true)
        protected List<com.pirc.commerc.Скидка> скидка;

        /**
         * Gets the value of the скидка property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the скидка property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getСкидка().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.pirc.commerc.Скидка }
         * 
         * 
         */
        public List<com.pirc.commerc.Скидка> getСкидка() {
            if (скидка == null) {
                скидка = new ArrayList<com.pirc.commerc.Скидка>();
            }
            return this.скидка;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Склад" type="{urn:1C.ru:commerceml_2}Склад" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0441\u043a\u043b\u0430\u0434"
    })
    public static class Склады {

        @XmlElement(name = "\u0421\u043a\u043b\u0430\u0434", required = true)
        protected List<com.pirc.commerc.Склад> склад;

        /**
         * Gets the value of the склад property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the склад property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getСклад().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.pirc.commerc.Склад }
         * 
         * 
         */
        public List<com.pirc.commerc.Склад> getСклад() {
            if (склад == null) {
                склад = new ArrayList<com.pirc.commerc.Склад>();
            }
            return this.склад;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Товар" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
     *                 &lt;sequence>
     *                   &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
     *                   &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
     *                   &lt;element name="ЦенаЗаЕдиницу" type="{urn:1C.ru:commerceml_2}СуммаТип" minOccurs="0"/>
     *                   &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
     *                   &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип" minOccurs="0"/>
     *                   &lt;group ref="{urn:1C.ru:commerceml_2}ЕдиницаИзмерения" minOccurs="0"/>
     *                   &lt;element name="СтранаПроисхождения" type="{urn:1C.ru:commerceml_2}СтрокаТип" minOccurs="0"/>
     *                   &lt;element name="ГТД" type="{urn:1C.ru:commerceml_2}СтрокаТип" minOccurs="0"/>
     *                   &lt;element name="Налоги" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Налог" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{urn:1C.ru:commerceml_2}Налог">
     *                                     &lt;sequence>
     *                                       &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
     *                                       &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Скидки" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Скидка" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{urn:1C.ru:commerceml_2}Скидка">
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ДопРасходы" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ДопРасход" type="{urn:1C.ru:commerceml_2}ДопРасход" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ДополнительныеЗначенияРеквизитов" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ЗначениеРеквизита" type="{urn:1C.ru:commerceml_2}ЗначениеРеквизита" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Склады" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Склад" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{urn:1C.ru:commerceml_2}Склад">
     *                                     &lt;sequence>
     *                                       &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0442\u043e\u0432\u0430\u0440"
    })
    public static class Товары {

        @XmlElement(name = "\u0422\u043e\u0432\u0430\u0440", required = true)
        protected List<Документ.Товары.Товар> товар;

        /**
         * Gets the value of the товар property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the товар property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getТовар().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Документ.Товары.Товар }
         * 
         * 
         */
        public List<Документ.Товары.Товар> getТовар() {
            if (товар == null) {
                товар = new ArrayList<Документ.Товары.Товар>();
            }
            return this.товар;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
         *       &lt;sequence>
         *         &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
         *         &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
         *         &lt;element name="ЦенаЗаЕдиницу" type="{urn:1C.ru:commerceml_2}СуммаТип" minOccurs="0"/>
         *         &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
         *         &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип" minOccurs="0"/>
         *         &lt;group ref="{urn:1C.ru:commerceml_2}ЕдиницаИзмерения" minOccurs="0"/>
         *         &lt;element name="СтранаПроисхождения" type="{urn:1C.ru:commerceml_2}СтрокаТип" minOccurs="0"/>
         *         &lt;element name="ГТД" type="{urn:1C.ru:commerceml_2}СтрокаТип" minOccurs="0"/>
         *         &lt;element name="Налоги" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Налог" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{urn:1C.ru:commerceml_2}Налог">
         *                           &lt;sequence>
         *                             &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
         *                             &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Скидки" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Скидка" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{urn:1C.ru:commerceml_2}Скидка">
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ДопРасходы" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ДопРасход" type="{urn:1C.ru:commerceml_2}ДопРасход" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ДополнительныеЗначенияРеквизитов" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ЗначениеРеквизита" type="{urn:1C.ru:commerceml_2}ЗначениеРеквизита" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Склады" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Склад" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{urn:1C.ru:commerceml_2}Склад">
         *                           &lt;sequence>
         *                             &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "\u0438\u0434\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0430",
            "\u0438\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430",
            "\u0446\u0435\u043d\u0430\u0417\u0430\u0415\u0434\u0438\u043d\u0438\u0446\u0443",
            "\u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e",
            "\u0441\u0443\u043c\u043c\u0430",
            "\u0435\u0434\u0438\u043d\u0438\u0446\u0430",
            "\u043a\u043e\u044d\u0444\u0444\u0438\u0446\u0438\u0435\u043d\u0442",
            "\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435\u0414\u0430\u043d\u043d\u044b\u0435",
            "\u0441\u0442\u0440\u0430\u043d\u0430\u041f\u0440\u043e\u0438\u0441\u0445\u043e\u0436\u0434\u0435\u043d\u0438\u044f",
            "\u0433\u0442\u0434",
            "\u043d\u0430\u043b\u043e\u0433\u0438",
            "\u0441\u043a\u0438\u0434\u043a\u0438",
            "\u0434\u043e\u043f\u0420\u0430\u0441\u0445\u043e\u0434\u044b",
            "\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u043e\u0432",
            "\u0441\u043a\u043b\u0430\u0434\u044b"
        })
        public static class Товар
            extends com.pirc.commerc.Товар
        {

            @XmlElement(name = "\u0418\u0434\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0430")
            protected String идКаталога;
            @XmlElement(name = "\u0418\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430")
            protected String идКлассификатора;
            @XmlElement(name = "\u0426\u0435\u043d\u0430\u0417\u0430\u0415\u0434\u0438\u043d\u0438\u0446\u0443")
            protected BigDecimal ценаЗаЕдиницу;
            @XmlElement(name = "\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e")
            protected BigDecimal количество;
            @XmlElement(name = "\u0421\u0443\u043c\u043c\u0430")
            protected BigDecimal сумма;
            @XmlElement(name = "\u0415\u0434\u0438\u043d\u0438\u0446\u0430")
            protected String единица;
            @XmlElement(name = "\u041a\u043e\u044d\u0444\u0444\u0438\u0446\u0438\u0435\u043d\u0442")
            protected String коэффициент;
            @XmlElement(name = "\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435\u0414\u0430\u043d\u043d\u044b\u0435")
            protected ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные дополнительныеДанные;
            @XmlElement(name = "\u0421\u0442\u0440\u0430\u043d\u0430\u041f\u0440\u043e\u0438\u0441\u0445\u043e\u0436\u0434\u0435\u043d\u0438\u044f")
            protected String странаПроисхождения;
            @XmlElement(name = "\u0413\u0422\u0414")
            protected String гтд;
            @XmlElement(name = "\u041d\u0430\u043b\u043e\u0433\u0438")
            protected Документ.Товары.Товар.Налоги налоги;
            @XmlElement(name = "\u0421\u043a\u0438\u0434\u043a\u0438")
            protected Документ.Товары.Товар.Скидки скидки;
            @XmlElement(name = "\u0414\u043e\u043f\u0420\u0430\u0441\u0445\u043e\u0434\u044b")
            protected Документ.Товары.Товар.ДопРасходы допРасходы;
            @XmlElement(name = "\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u043e\u0432")
            protected Документ.Товары.Товар.ДополнительныеЗначенияРеквизитов дополнительныеЗначенияРеквизитов;
            @XmlElement(name = "\u0421\u043a\u043b\u0430\u0434\u044b")
            protected Документ.Товары.Товар.Склады склады;

            /**
             * Gets the value of the идКаталога property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getИдКаталога() {
                return идКаталога;
            }

            /**
             * Sets the value of the идКаталога property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setИдКаталога(String value) {
                this.идКаталога = value;
            }

            /**
             * Gets the value of the идКлассификатора property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getИдКлассификатора() {
                return идКлассификатора;
            }

            /**
             * Sets the value of the идКлассификатора property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setИдКлассификатора(String value) {
                this.идКлассификатора = value;
            }

            /**
             * Gets the value of the ценаЗаЕдиницу property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getЦенаЗаЕдиницу() {
                return ценаЗаЕдиницу;
            }

            /**
             * Sets the value of the ценаЗаЕдиницу property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setЦенаЗаЕдиницу(BigDecimal value) {
                this.ценаЗаЕдиницу = value;
            }

            /**
             * Gets the value of the количество property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getКоличество() {
                return количество;
            }

            /**
             * Sets the value of the количество property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setКоличество(BigDecimal value) {
                this.количество = value;
            }

            /**
             * Gets the value of the сумма property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getСумма() {
                return сумма;
            }

            /**
             * Sets the value of the сумма property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setСумма(BigDecimal value) {
                this.сумма = value;
            }

            /**
             * Gets the value of the единица property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getЕдиница() {
                return единица;
            }

            /**
             * Sets the value of the единица property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setЕдиница(String value) {
                this.единица = value;
            }

            /**
             * Gets the value of the коэффициент property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getКоэффициент() {
                return коэффициент;
            }

            /**
             * Sets the value of the коэффициент property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setКоэффициент(String value) {
                this.коэффициент = value;
            }

            /**
             * Gets the value of the дополнительныеДанные property.
             * 
             * @return
             *     possible object is
             *     {@link ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные }
             *     
             */
            public ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные getДополнительныеДанные() {
                return дополнительныеДанные;
            }

            /**
             * Sets the value of the дополнительныеДанные property.
             * 
             * @param value
             *     allowed object is
             *     {@link ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные }
             *     
             */
            public void setДополнительныеДанные(ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные value) {
                this.дополнительныеДанные = value;
            }

            /**
             * Gets the value of the странаПроисхождения property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getСтранаПроисхождения() {
                return странаПроисхождения;
            }

            /**
             * Sets the value of the странаПроисхождения property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setСтранаПроисхождения(String value) {
                this.странаПроисхождения = value;
            }

            /**
             * Gets the value of the гтд property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getГТД() {
                return гтд;
            }

            /**
             * Sets the value of the гтд property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setГТД(String value) {
                this.гтд = value;
            }

            /**
             * Gets the value of the налоги property.
             * 
             * @return
             *     possible object is
             *     {@link Документ.Товары.Товар.Налоги }
             *     
             */
            public Документ.Товары.Товар.Налоги getНалоги() {
                return налоги;
            }

            /**
             * Sets the value of the налоги property.
             * 
             * @param value
             *     allowed object is
             *     {@link Документ.Товары.Товар.Налоги }
             *     
             */
            public void setНалоги(Документ.Товары.Товар.Налоги value) {
                this.налоги = value;
            }

            /**
             * Gets the value of the скидки property.
             * 
             * @return
             *     possible object is
             *     {@link Документ.Товары.Товар.Скидки }
             *     
             */
            public Документ.Товары.Товар.Скидки getСкидки() {
                return скидки;
            }

            /**
             * Sets the value of the скидки property.
             * 
             * @param value
             *     allowed object is
             *     {@link Документ.Товары.Товар.Скидки }
             *     
             */
            public void setСкидки(Документ.Товары.Товар.Скидки value) {
                this.скидки = value;
            }

            /**
             * Gets the value of the допРасходы property.
             * 
             * @return
             *     possible object is
             *     {@link Документ.Товары.Товар.ДопРасходы }
             *     
             */
            public Документ.Товары.Товар.ДопРасходы getДопРасходы() {
                return допРасходы;
            }

            /**
             * Sets the value of the допРасходы property.
             * 
             * @param value
             *     allowed object is
             *     {@link Документ.Товары.Товар.ДопРасходы }
             *     
             */
            public void setДопРасходы(Документ.Товары.Товар.ДопРасходы value) {
                this.допРасходы = value;
            }

            /**
             * Gets the value of the дополнительныеЗначенияРеквизитов property.
             * 
             * @return
             *     possible object is
             *     {@link Документ.Товары.Товар.ДополнительныеЗначенияРеквизитов }
             *     
             */
            public Документ.Товары.Товар.ДополнительныеЗначенияРеквизитов getДополнительныеЗначенияРеквизитов() {
                return дополнительныеЗначенияРеквизитов;
            }

            /**
             * Sets the value of the дополнительныеЗначенияРеквизитов property.
             * 
             * @param value
             *     allowed object is
             *     {@link Документ.Товары.Товар.ДополнительныеЗначенияРеквизитов }
             *     
             */
            public void setДополнительныеЗначенияРеквизитов(Документ.Товары.Товар.ДополнительныеЗначенияРеквизитов value) {
                this.дополнительныеЗначенияРеквизитов = value;
            }

            /**
             * Gets the value of the склады property.
             * 
             * @return
             *     possible object is
             *     {@link Документ.Товары.Товар.Склады }
             *     
             */
            public Документ.Товары.Товар.Склады getСклады() {
                return склады;
            }

            /**
             * Sets the value of the склады property.
             * 
             * @param value
             *     allowed object is
             *     {@link Документ.Товары.Товар.Склады }
             *     
             */
            public void setСклады(Документ.Товары.Товар.Склады value) {
                this.склады = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ДопРасход" type="{urn:1C.ru:commerceml_2}ДопРасход" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "\u0434\u043e\u043f\u0420\u0430\u0441\u0445\u043e\u0434"
            })
            public static class ДопРасходы {

                @XmlElement(name = "\u0414\u043e\u043f\u0420\u0430\u0441\u0445\u043e\u0434", required = true)
                protected List<ДопРасход> допРасход;

                /**
                 * Gets the value of the допРасход property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the допРасход property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getДопРасход().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ДопРасход }
                 * 
                 * 
                 */
                public List<ДопРасход> getДопРасход() {
                    if (допРасход == null) {
                        допРасход = new ArrayList<ДопРасход>();
                    }
                    return this.допРасход;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ЗначениеРеквизита" type="{urn:1C.ru:commerceml_2}ЗначениеРеквизита" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u0430"
            })
            public static class ДополнительныеЗначенияРеквизитов {

                @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u0430", required = true)
                protected List<ЗначениеРеквизита> значениеРеквизита;

                /**
                 * Gets the value of the значениеРеквизита property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the значениеРеквизита property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getЗначениеРеквизита().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ЗначениеРеквизита }
                 * 
                 * 
                 */
                public List<ЗначениеРеквизита> getЗначениеРеквизита() {
                    if (значениеРеквизита == null) {
                        значениеРеквизита = new ArrayList<ЗначениеРеквизита>();
                    }
                    return this.значениеРеквизита;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Налог" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{urn:1C.ru:commerceml_2}Налог">
             *                 &lt;sequence>
             *                   &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
             *                   &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "\u043d\u0430\u043b\u043e\u0433"
            })
            public static class Налоги {

                @XmlElement(name = "\u041d\u0430\u043b\u043e\u0433", required = true)
                protected List<Документ.Товары.Товар.Налоги.Налог> налог;

                /**
                 * Gets the value of the налог property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the налог property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getНалог().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Документ.Товары.Товар.Налоги.Налог }
                 * 
                 * 
                 */
                public List<Документ.Товары.Товар.Налоги.Налог> getНалог() {
                    if (налог == null) {
                        налог = new ArrayList<Документ.Товары.Товар.Налоги.Налог>();
                    }
                    return this.налог;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{urn:1C.ru:commerceml_2}Налог">
                 *       &lt;sequence>
                 *         &lt;element name="Сумма" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
                 *         &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "\u0441\u0443\u043c\u043c\u0430",
                    "\u0441\u0442\u0430\u0432\u043a\u0430"
                })
                public static class Налог
                    extends com.pirc.commerc.Налог
                {

                    @XmlElement(name = "\u0421\u0443\u043c\u043c\u0430", required = true)
                    protected BigDecimal сумма;
                    @XmlElement(name = "\u0421\u0442\u0430\u0432\u043a\u0430")
                    protected String ставка;

                    /**
                     * Gets the value of the сумма property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getСумма() {
                        return сумма;
                    }

                    /**
                     * Sets the value of the сумма property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setСумма(BigDecimal value) {
                        this.сумма = value;
                    }

                    /**
                     * Gets the value of the ставка property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getСтавка() {
                        return ставка;
                    }

                    /**
                     * Sets the value of the ставка property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setСтавка(String value) {
                        this.ставка = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Скидка" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{urn:1C.ru:commerceml_2}Скидка">
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "\u0441\u043a\u0438\u0434\u043a\u0430"
            })
            public static class Скидки {

                @XmlElement(name = "\u0421\u043a\u0438\u0434\u043a\u0430", required = true)
                protected List<Документ.Товары.Товар.Скидки.Скидка> скидка;

                /**
                 * Gets the value of the скидка property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the скидка property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getСкидка().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Документ.Товары.Товар.Скидки.Скидка }
                 * 
                 * 
                 */
                public List<Документ.Товары.Товар.Скидки.Скидка> getСкидка() {
                    if (скидка == null) {
                        скидка = new ArrayList<Документ.Товары.Товар.Скидки.Скидка>();
                    }
                    return this.скидка;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{urn:1C.ru:commerceml_2}Скидка">
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Скидка
                    extends com.pirc.commerc.Скидка
                {


                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Склад" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{urn:1C.ru:commerceml_2}Склад">
             *                 &lt;sequence>
             *                   &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "\u0441\u043a\u043b\u0430\u0434"
            })
            public static class Склады {

                @XmlElement(name = "\u0421\u043a\u043b\u0430\u0434", required = true)
                protected List<Документ.Товары.Товар.Склады.Склад> склад;

                /**
                 * Gets the value of the склад property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the склад property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getСклад().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Документ.Товары.Товар.Склады.Склад }
                 * 
                 * 
                 */
                public List<Документ.Товары.Товар.Склады.Склад> getСклад() {
                    if (склад == null) {
                        склад = new ArrayList<Документ.Товары.Товар.Склады.Склад>();
                    }
                    return this.склад;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{urn:1C.ru:commerceml_2}Склад">
                 *       &lt;sequence>
                 *         &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "\u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e"
                })
                public static class Склад
                    extends com.pirc.commerc.Склад
                {

                    @XmlElement(name = "\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e")
                    protected BigDecimal количество;

                    /**
                     * Gets the value of the количество property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getКоличество() {
                        return количество;
                    }

                    /**
                     * Sets the value of the количество property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setКоличество(BigDecimal value) {
                        this.количество = value;
                    }

                }

            }

        }

    }

}
