//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Изменения публикуемых предложений - для быстрой загрузки на сайт
 * 
 * <p>Java class for ИзмененияПакетаПредложений complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ИзмененияПакетаПредложений">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ид" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип"/>
 *         &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *         &lt;element name="Предложения" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Предложение" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;group ref="{urn:1C.ru:commerceml_2}ИдентификаторТовара"/>
 *                             &lt;element name="ИдХарактеристики" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *                             &lt;element name="КодЕдиницыИзмерения" type="{urn:1C.ru:commerceml_2}ЕдиницаТип" minOccurs="0"/>
 *                             &lt;element name="Склады" type="{urn:1C.ru:commerceml_2}ОстаткиПоСкладам" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="Цены" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Цена" type="{urn:1C.ru:commerceml_2}Цена" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="СодержитТолькоИзменения" type="{urn:1C.ru:commerceml_2}ПереключательТип" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0418\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f\u041f\u0430\u043a\u0435\u0442\u0430\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439", propOrder = {
    "\u0438\u0434",
    "\u0438\u0434\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0430",
    "\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f"
})
public class ИзмененияПакетаПредложений {

    @XmlElement(name = "\u0418\u0434", required = true)
    protected String ид;
    @XmlElement(name = "\u0418\u0434\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0430")
    protected String идКаталога;
    @XmlElement(name = "\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f")
    protected ИзмененияПакетаПредложений.Предложения предложения;
    @XmlAttribute(name = "\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u0442\u0422\u043e\u043b\u044c\u043a\u043e\u0418\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f")
    protected Boolean содержитТолькоИзменения;

    /**
     * Gets the value of the ид property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИд() {
        return ид;
    }

    /**
     * Sets the value of the ид property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИд(String value) {
        this.ид = value;
    }

    /**
     * Gets the value of the идКаталога property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдКаталога() {
        return идКаталога;
    }

    /**
     * Sets the value of the идКаталога property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдКаталога(String value) {
        this.идКаталога = value;
    }

    /**
     * Gets the value of the предложения property.
     * 
     * @return
     *     possible object is
     *     {@link ИзмененияПакетаПредложений.Предложения }
     *     
     */
    public ИзмененияПакетаПредложений.Предложения getПредложения() {
        return предложения;
    }

    /**
     * Sets the value of the предложения property.
     * 
     * @param value
     *     allowed object is
     *     {@link ИзмененияПакетаПредложений.Предложения }
     *     
     */
    public void setПредложения(ИзмененияПакетаПредложений.Предложения value) {
        this.предложения = value;
    }

    /**
     * Gets the value of the содержитТолькоИзменения property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isСодержитТолькоИзменения() {
        return содержитТолькоИзменения;
    }

    /**
     * Sets the value of the содержитТолькоИзменения property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setСодержитТолькоИзменения(Boolean value) {
        this.содержитТолькоИзменения = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Предложение" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;group ref="{urn:1C.ru:commerceml_2}ИдентификаторТовара"/>
     *                   &lt;element name="ИдХарактеристики" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
     *                   &lt;element name="КодЕдиницыИзмерения" type="{urn:1C.ru:commerceml_2}ЕдиницаТип" minOccurs="0"/>
     *                   &lt;element name="Склады" type="{urn:1C.ru:commerceml_2}ОстаткиПоСкладам" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Цены" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Цена" type="{urn:1C.ru:commerceml_2}Цена" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435"
    })
    public static class Предложения {

        @XmlElement(name = "\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435", required = true)
        protected List<ИзмененияПакетаПредложений.Предложения.Предложение> предложение;

        /**
         * Gets the value of the предложение property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the предложение property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getПредложение().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ИзмененияПакетаПредложений.Предложения.Предложение }
         * 
         * 
         */
        public List<ИзмененияПакетаПредложений.Предложения.Предложение> getПредложение() {
            if (предложение == null) {
                предложение = new ArrayList<ИзмененияПакетаПредложений.Предложения.Предложение>();
            }
            return this.предложение;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;group ref="{urn:1C.ru:commerceml_2}ИдентификаторТовара"/>
         *         &lt;element name="ИдХарактеристики" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
         *         &lt;element name="КодЕдиницыИзмерения" type="{urn:1C.ru:commerceml_2}ЕдиницаТип" minOccurs="0"/>
         *         &lt;element name="Склады" type="{urn:1C.ru:commerceml_2}ОстаткиПоСкладам" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Цены" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Цена" type="{urn:1C.ru:commerceml_2}Цена" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "\u0438\u0434",
            "\u0448\u0442\u0440\u0438\u0445\u043a\u043e\u0434",
            "\u0430\u0440\u0442\u0438\u043a\u0443\u043b",
            "\u0438\u0434\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438",
            "\u043a\u043e\u0434\u0415\u0434\u0438\u043d\u0438\u0446\u044b\u0418\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f",
            "\u0441\u043a\u043b\u0430\u0434\u044b",
            "\u0446\u0435\u043d\u044b",
            "\u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e"
        })
        public static class Предложение {

            @XmlElement(name = "\u0418\u0434")
            protected String ид;
            @XmlElement(name = "\u0428\u0442\u0440\u0438\u0445\u043a\u043e\u0434")
            protected String штрихкод;
            @XmlElement(name = "\u0410\u0440\u0442\u0438\u043a\u0443\u043b")
            protected String артикул;
            @XmlElement(name = "\u0418\u0434\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438")
            protected String идХарактеристики;
            @XmlElement(name = "\u041a\u043e\u0434\u0415\u0434\u0438\u043d\u0438\u0446\u044b\u0418\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f")
            protected String кодЕдиницыИзмерения;
            @XmlElement(name = "\u0421\u043a\u043b\u0430\u0434\u044b")
            protected List<ОстаткиПоСкладам> склады;
            @XmlElement(name = "\u0426\u0435\u043d\u044b")
            protected ИзмененияПакетаПредложений.Предложения.Предложение.Цены цены;
            @XmlElement(name = "\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e")
            protected BigDecimal количество;

            /**
             * Gets the value of the ид property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getИд() {
                return ид;
            }

            /**
             * Sets the value of the ид property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setИд(String value) {
                this.ид = value;
            }

            /**
             * Gets the value of the штрихкод property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getШтрихкод() {
                return штрихкод;
            }

            /**
             * Sets the value of the штрихкод property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setШтрихкод(String value) {
                this.штрихкод = value;
            }

            /**
             * Gets the value of the артикул property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getАртикул() {
                return артикул;
            }

            /**
             * Sets the value of the артикул property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setАртикул(String value) {
                this.артикул = value;
            }

            /**
             * Gets the value of the идХарактеристики property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getИдХарактеристики() {
                return идХарактеристики;
            }

            /**
             * Sets the value of the идХарактеристики property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setИдХарактеристики(String value) {
                this.идХарактеристики = value;
            }

            /**
             * Gets the value of the кодЕдиницыИзмерения property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getКодЕдиницыИзмерения() {
                return кодЕдиницыИзмерения;
            }

            /**
             * Sets the value of the кодЕдиницыИзмерения property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setКодЕдиницыИзмерения(String value) {
                this.кодЕдиницыИзмерения = value;
            }

            /**
             * Gets the value of the склады property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the склады property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getСклады().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ОстаткиПоСкладам }
             * 
             * 
             */
            public List<ОстаткиПоСкладам> getСклады() {
                if (склады == null) {
                    склады = new ArrayList<ОстаткиПоСкладам>();
                }
                return this.склады;
            }

            /**
             * Gets the value of the цены property.
             * 
             * @return
             *     possible object is
             *     {@link ИзмененияПакетаПредложений.Предложения.Предложение.Цены }
             *     
             */
            public ИзмененияПакетаПредложений.Предложения.Предложение.Цены getЦены() {
                return цены;
            }

            /**
             * Sets the value of the цены property.
             * 
             * @param value
             *     allowed object is
             *     {@link ИзмененияПакетаПредложений.Предложения.Предложение.Цены }
             *     
             */
            public void setЦены(ИзмененияПакетаПредложений.Предложения.Предложение.Цены value) {
                this.цены = value;
            }

            /**
             * Gets the value of the количество property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getКоличество() {
                return количество;
            }

            /**
             * Sets the value of the количество property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setКоличество(BigDecimal value) {
                this.количество = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Цена" type="{urn:1C.ru:commerceml_2}Цена" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "\u0446\u0435\u043d\u0430"
            })
            public static class Цены {

                @XmlElement(name = "\u0426\u0435\u043d\u0430", required = true)
                protected List<Цена> цена;

                /**
                 * Gets the value of the цена property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the цена property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getЦена().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Цена }
                 * 
                 * 
                 */
                public List<Цена> getЦена() {
                    if (цена == null) {
                        цена = new ArrayList<Цена>();
                    }
                    return this.цена;
                }

            }

        }

    }

}
