//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Каталог товаров содержит перечень товаров. Может составляться разными предприятиями (например, каталог продукции фирмы «1С»). У каталога всегда определен владелец, а товары могут описываться по классификатору.
 * 
 * <p>Java class for Каталог complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Каталог">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ид" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип"/>
 *         &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *         &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}НаименованиеТип"/>
 *         &lt;element name="Владелец" type="{urn:1C.ru:commerceml_2}Контрагент"/>
 *         &lt;element name="Товары">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Товар" type="{urn:1C.ru:commerceml_2}Товар" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Описание" type="{urn:1C.ru:commerceml_2}КомментарийТип" minOccurs="0"/>
 *         &lt;element name="Подписанты" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Подписант" type="{urn:1C.ru:commerceml_2}Подписант" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="СодержитТолькоИзменения" type="{urn:1C.ru:commerceml_2}ПереключательТип" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u041a\u0430\u0442\u0430\u043b\u043e\u0433", propOrder = {
    "\u0438\u0434",
    "\u0438\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430",
    "\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435",
    "\u0432\u043b\u0430\u0434\u0435\u043b\u0435\u0446",
    "\u0442\u043e\u0432\u0430\u0440\u044b",
    "\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435",
    "\u043f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u044b"
})
public class Каталог {

    @XmlElement(name = "\u0418\u0434", required = true)
    protected String ид;
    @XmlElement(name = "\u0418\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430")
    protected String идКлассификатора;
    @XmlElement(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", required = true)
    protected String наименование;
    @XmlElement(name = "\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446", required = true)
    protected Контрагент владелец;
    @XmlElement(name = "\u0422\u043e\u0432\u0430\u0440\u044b", required = true)
    protected Каталог.Товары товары;
    @XmlElement(name = "\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435")
    protected String описание;
    @XmlElement(name = "\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u044b")
    protected Каталог.Подписанты подписанты;
    @XmlAttribute(name = "\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u0442\u0422\u043e\u043b\u044c\u043a\u043e\u0418\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f")
    protected Boolean содержитТолькоИзменения;

    /**
     * Gets the value of the ид property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИд() {
        return ид;
    }

    /**
     * Sets the value of the ид property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИд(String value) {
        this.ид = value;
    }

    /**
     * Gets the value of the идКлассификатора property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдКлассификатора() {
        return идКлассификатора;
    }

    /**
     * Sets the value of the идКлассификатора property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдКлассификатора(String value) {
        this.идКлассификатора = value;
    }

    /**
     * Gets the value of the наименование property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНаименование() {
        return наименование;
    }

    /**
     * Sets the value of the наименование property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНаименование(String value) {
        this.наименование = value;
    }

    /**
     * Gets the value of the владелец property.
     * 
     * @return
     *     possible object is
     *     {@link Контрагент }
     *     
     */
    public Контрагент getВладелец() {
        return владелец;
    }

    /**
     * Sets the value of the владелец property.
     * 
     * @param value
     *     allowed object is
     *     {@link Контрагент }
     *     
     */
    public void setВладелец(Контрагент value) {
        this.владелец = value;
    }

    /**
     * Gets the value of the товары property.
     * 
     * @return
     *     possible object is
     *     {@link Каталог.Товары }
     *     
     */
    public Каталог.Товары getТовары() {
        return товары;
    }

    /**
     * Sets the value of the товары property.
     * 
     * @param value
     *     allowed object is
     *     {@link Каталог.Товары }
     *     
     */
    public void setТовары(Каталог.Товары value) {
        this.товары = value;
    }

    /**
     * Gets the value of the описание property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОписание() {
        return описание;
    }

    /**
     * Sets the value of the описание property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОписание(String value) {
        this.описание = value;
    }

    /**
     * Gets the value of the подписанты property.
     * 
     * @return
     *     possible object is
     *     {@link Каталог.Подписанты }
     *     
     */
    public Каталог.Подписанты getПодписанты() {
        return подписанты;
    }

    /**
     * Sets the value of the подписанты property.
     * 
     * @param value
     *     allowed object is
     *     {@link Каталог.Подписанты }
     *     
     */
    public void setПодписанты(Каталог.Подписанты value) {
        this.подписанты = value;
    }

    /**
     * Gets the value of the содержитТолькоИзменения property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isСодержитТолькоИзменения() {
        return содержитТолькоИзменения;
    }

    /**
     * Sets the value of the содержитТолькоИзменения property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setСодержитТолькоИзменения(Boolean value) {
        this.содержитТолькоИзменения = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Подписант" type="{urn:1C.ru:commerceml_2}Подписант" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442"
    })
    public static class Подписанты {

        @XmlElement(name = "\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442", required = true)
        protected List<Подписант> подписант;

        /**
         * Gets the value of the подписант property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the подписант property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getПодписант().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Подписант }
         * 
         * 
         */
        public List<Подписант> getПодписант() {
            if (подписант == null) {
                подписант = new ArrayList<Подписант>();
            }
            return this.подписант;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Товар" type="{urn:1C.ru:commerceml_2}Товар" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0442\u043e\u0432\u0430\u0440"
    })
    public static class Товары {

        @XmlElement(name = "\u0422\u043e\u0432\u0430\u0440", required = true)
        protected List<Товар> товар;

        /**
         * Gets the value of the товар property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the товар property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getТовар().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Товар }
         * 
         * 
         */
        public List<Товар> getТовар() {
            if (товар == null) {
                товар = new ArrayList<Товар>();
            }
            return this.товар;
        }

    }

}
