//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Собирательный компонент для всего, что может быть упомянуто в процессе обмена 
 * 
 * <p>Java class for КоммерческаяИнформация1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="КоммерческаяИнформация1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:1C.ru:commerceml_2}Классификатор" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{urn:1C.ru:commerceml_2}Каталог" minOccurs="0"/>
 *           &lt;element ref="{urn:1C.ru:commerceml_2}ПакетПредложений" minOccurs="0"/>
 *           &lt;element ref="{urn:1C.ru:commerceml_2}Документ" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{urn:1C.ru:commerceml_2}ИзмененияПакетаПредложений" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="ВерсияСхемы" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="5"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ДатаФормирования" use="required" type="{urn:1C.ru:commerceml_2}ДатаВремяТип" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u041a\u043e\u043c\u043c\u0435\u0440\u0447\u0435\u0441\u043a\u0430\u044f\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f1", propOrder = {
    "\u043a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440",
    "\u043a\u0430\u0442\u0430\u043b\u043e\u0433",
    "\u043f\u0430\u043a\u0435\u0442\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439",
    "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442",
    "\u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f\u041f\u0430\u043a\u0435\u0442\u0430\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439"
})
@XmlSeeAlso({
    КоммерческаяИнформация.class
})
public class КоммерческаяИнформация1 {

    @XmlElement(name = "\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440")
    protected Классификатор классификатор;
    @XmlElement(name = "\u041a\u0430\u0442\u0430\u043b\u043e\u0433")
    protected Каталог каталог;
    @XmlElement(name = "\u041f\u0430\u043a\u0435\u0442\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439")
    protected ПакетПредложений пакетПредложений;
    @XmlElement(name = "\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442")
    protected List<Документ> документ;
    @XmlElement(name = "\u0418\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f\u041f\u0430\u043a\u0435\u0442\u0430\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439")
    protected List<ИзмененияПакетаПредложений> измененияПакетаПредложений;
    @XmlAttribute(name = "\u0412\u0435\u0440\u0441\u0438\u044f\u0421\u0445\u0435\u043c\u044b", required = true)
    protected String версияСхемы;
    @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u0424\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f", required = true)
    protected XMLGregorianCalendar датаФормирования;

    /**
     * Gets the value of the классификатор property.
     * 
     * @return
     *     possible object is
     *     {@link Классификатор }
     *     
     */
    public Классификатор getКлассификатор() {
        return классификатор;
    }

    /**
     * Sets the value of the классификатор property.
     * 
     * @param value
     *     allowed object is
     *     {@link Классификатор }
     *     
     */
    public void setКлассификатор(Классификатор value) {
        this.классификатор = value;
    }

    /**
     * Gets the value of the каталог property.
     * 
     * @return
     *     possible object is
     *     {@link Каталог }
     *     
     */
    public Каталог getКаталог() {
        return каталог;
    }

    /**
     * Sets the value of the каталог property.
     * 
     * @param value
     *     allowed object is
     *     {@link Каталог }
     *     
     */
    public void setКаталог(Каталог value) {
        this.каталог = value;
    }

    /**
     * Gets the value of the пакетПредложений property.
     * 
     * @return
     *     possible object is
     *     {@link ПакетПредложений }
     *     
     */
    public ПакетПредложений getПакетПредложений() {
        return пакетПредложений;
    }

    /**
     * Sets the value of the пакетПредложений property.
     * 
     * @param value
     *     allowed object is
     *     {@link ПакетПредложений }
     *     
     */
    public void setПакетПредложений(ПакетПредложений value) {
        this.пакетПредложений = value;
    }

    /**
     * Gets the value of the документ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the документ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getДокумент().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Документ }
     * 
     * 
     */
    public List<Документ> getДокумент() {
        if (документ == null) {
            документ = new ArrayList<Документ>();
        }
        return this.документ;
    }

    /**
     * Gets the value of the измененияПакетаПредложений property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the измененияПакетаПредложений property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getИзмененияПакетаПредложений().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ИзмененияПакетаПредложений }
     * 
     * 
     */
    public List<ИзмененияПакетаПредложений> getИзмененияПакетаПредложений() {
        if (измененияПакетаПредложений == null) {
            измененияПакетаПредложений = new ArrayList<ИзмененияПакетаПредложений>();
        }
        return this.измененияПакетаПредложений;
    }

    /**
     * Gets the value of the версияСхемы property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getВерсияСхемы() {
        return версияСхемы;
    }

    /**
     * Sets the value of the версияСхемы property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setВерсияСхемы(String value) {
        this.версияСхемы = value;
    }

    /**
     * Gets the value of the датаФормирования property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДатаФормирования() {
        return датаФормирования;
    }

    /**
     * Sets the value of the датаФормирования property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДатаФормирования(XMLGregorianCalendar value) {
        this.датаФормирования = value;
    }

}
