//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Содержит описание возможных способов связи (по телефону, электронной почте и т.д.)
 * 
 * <p>Java class for КонтактнаяИнформация complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="КонтактнаяИнформация">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Контакт" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Тип" type="{urn:1C.ru:commerceml_2}КонтактТип"/>
 *                   &lt;element name="Значение" type="{urn:1C.ru:commerceml_2}СтрокаТип"/>
 *                   &lt;element name="Комментарий" type="{urn:1C.ru:commerceml_2}КомментарийТип" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u0430\u044f\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f", propOrder = {
    "\u043a\u043e\u043d\u0442\u0430\u043a\u0442"
})
public class КонтактнаяИнформация {

    @XmlElement(name = "\u041a\u043e\u043d\u0442\u0430\u043a\u0442", required = true)
    protected List<КонтактнаяИнформация.Контакт> контакт;

    /**
     * Gets the value of the контакт property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the контакт property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getКонтакт().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link КонтактнаяИнформация.Контакт }
     * 
     * 
     */
    public List<КонтактнаяИнформация.Контакт> getКонтакт() {
        if (контакт == null) {
            контакт = new ArrayList<КонтактнаяИнформация.Контакт>();
        }
        return this.контакт;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Тип" type="{urn:1C.ru:commerceml_2}КонтактТип"/>
     *         &lt;element name="Значение" type="{urn:1C.ru:commerceml_2}СтрокаТип"/>
     *         &lt;element name="Комментарий" type="{urn:1C.ru:commerceml_2}КомментарийТип" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0442\u0438\u043f",
        "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435",
        "\u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439"
    })
    public static class Контакт {

        @XmlElement(name = "\u0422\u0438\u043f", required = true)
        @XmlSchemaType(name = "string")
        protected КонтактТип тип;
        @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435", required = true)
        protected String значение;
        @XmlElement(name = "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439")
        protected String комментарий;

        /**
         * Gets the value of the тип property.
         * 
         * @return
         *     possible object is
         *     {@link КонтактТип }
         *     
         */
        public КонтактТип getТип() {
            return тип;
        }

        /**
         * Sets the value of the тип property.
         * 
         * @param value
         *     allowed object is
         *     {@link КонтактТип }
         *     
         */
        public void setТип(КонтактТип value) {
            this.тип = value;
        }

        /**
         * Gets the value of the значение property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getЗначение() {
            return значение;
        }

        /**
         * Sets the value of the значение property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setЗначение(String value) {
            this.значение = value;
        }

        /**
         * Gets the value of the комментарий property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getКомментарий() {
            return комментарий;
        }

        /**
         * Sets the value of the комментарий property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setКомментарий(String value) {
            this.комментарий = value;
        }

    }

}
