//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for КонтактТип.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="КонтактТип">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="100"/>
 *     &lt;enumeration value="Телефон внутренний"/>
 *     &lt;enumeration value="Телефон рабочий"/>
 *     &lt;enumeration value="Телефон мобильный"/>
 *     &lt;enumeration value="Телефон домашний"/>
 *     &lt;enumeration value="Пейджер"/>
 *     &lt;enumeration value="Факс"/>
 *     &lt;enumeration value="Почта"/>
 *     &lt;enumeration value="ICQ"/>
 *     &lt;enumeration value="ВебСайт"/>
 *     &lt;enumeration value="Координаты на карте"/>
 *     &lt;enumeration value="Прочее"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u0422\u0438\u043f")
@XmlEnum
public enum КонтактТип {

    @XmlEnumValue("\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u0432\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u0438\u0439")
    ТЕЛЕФОН_ВНУТРЕННИЙ("\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u0432\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u0438\u0439"),
    @XmlEnumValue("\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u0440\u0430\u0431\u043e\u0447\u0438\u0439")
    ТЕЛЕФОН_РАБОЧИЙ("\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u0440\u0430\u0431\u043e\u0447\u0438\u0439"),
    @XmlEnumValue("\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u043c\u043e\u0431\u0438\u043b\u044c\u043d\u044b\u0439")
    ТЕЛЕФОН_МОБИЛЬНЫЙ("\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u043c\u043e\u0431\u0438\u043b\u044c\u043d\u044b\u0439"),
    @XmlEnumValue("\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u0434\u043e\u043c\u0430\u0448\u043d\u0438\u0439")
    ТЕЛЕФОН_ДОМАШНИЙ("\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u0434\u043e\u043c\u0430\u0448\u043d\u0438\u0439"),
    @XmlEnumValue("\u041f\u0435\u0439\u0434\u0436\u0435\u0440")
    ПЕЙДЖЕР("\u041f\u0435\u0439\u0434\u0436\u0435\u0440"),
    @XmlEnumValue("\u0424\u0430\u043a\u0441")
    ФАКС("\u0424\u0430\u043a\u0441"),
    @XmlEnumValue("\u041f\u043e\u0447\u0442\u0430")
    ПОЧТА("\u041f\u043e\u0447\u0442\u0430"),
    ICQ("ICQ"),
    @XmlEnumValue("\u0412\u0435\u0431\u0421\u0430\u0439\u0442")
    ВЕБ_САЙТ("\u0412\u0435\u0431\u0421\u0430\u0439\u0442"),
    @XmlEnumValue("\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b \u043d\u0430 \u043a\u0430\u0440\u0442\u0435")
    КООРДИНАТЫ_НА_КАРТЕ("\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b \u043d\u0430 \u043a\u0430\u0440\u0442\u0435"),
    @XmlEnumValue("\u041f\u0440\u043e\u0447\u0435\u0435")
    ПРОЧЕЕ("\u041f\u0440\u043e\u0447\u0435\u0435");
    private final String value;

    КонтактТип(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static КонтактТип fromValue(String v) {
        for (КонтактТип c: КонтактТип.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
