//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Идентификатор склада и количество товаров на этом склате 
 * 
 * <p>Java class for ОстаткиПоСкладам complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ОстаткиПоСкладам">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ИдСклада" use="required" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" />
 *       &lt;attribute name="КоличествоНаСкладе" type="{urn:1C.ru:commerceml_2}КоличествоТип" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u041e\u0441\u0442\u0430\u0442\u043a\u0438\u041f\u043e\u0421\u043a\u043b\u0430\u0434\u0430\u043c")
public class ОстаткиПоСкладам {

    @XmlAttribute(name = "\u0418\u0434\u0421\u043a\u043b\u0430\u0434\u0430", required = true)
    protected String идСклада;
    @XmlAttribute(name = "\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e\u041d\u0430\u0421\u043a\u043b\u0430\u0434\u0435")
    protected BigDecimal количествоНаСкладе;

    /**
     * Gets the value of the идСклада property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдСклада() {
        return идСклада;
    }

    /**
     * Sets the value of the идСклада property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдСклада(String value) {
        this.идСклада = value;
    }

    /**
     * Gets the value of the количествоНаСкладе property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getКоличествоНаСкладе() {
        return количествоНаСкладе;
    }

    /**
     * Sets the value of the количествоНаСкладе property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setКоличествоНаСкладе(BigDecimal value) {
        this.количествоНаСкладе = value;
    }

}
