//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Содержит перечень коммерческих предложений. Пакет предложений составляется по определенному (только одному) каталогу, а предложения в пакете могут быть описаны по классификатору.
 * 
 * <p>Java class for ПакетПредложений complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ПакетПредложений">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ид" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *         &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}НаименованиеТип"/>
 *         &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип"/>
 *         &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *         &lt;element name="ДействительноС" type="{urn:1C.ru:commerceml_2}ДатаТип" minOccurs="0"/>
 *         &lt;element name="ДействительноДо" type="{urn:1C.ru:commerceml_2}ДатаТип" minOccurs="0"/>
 *         &lt;element name="Описание" type="{urn:1C.ru:commerceml_2}КомментарийТип" minOccurs="0"/>
 *         &lt;element name="Владелец" type="{urn:1C.ru:commerceml_2}Контрагент"/>
 *         &lt;element name="ТипыЦен">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *                   &lt;element name="ТипЦены" type="{urn:1C.ru:commerceml_2}ТипЦены" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Склады" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Склад" type="{urn:1C.ru:commerceml_2}Склад" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ЗначенияСвойств" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ЗначенияСвойства" type="{urn:1C.ru:commerceml_2}ЗначенияСвойства" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Предложения">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Предложение" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
 *                           &lt;sequence>
 *                             &lt;element name="Цены">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Цена" type="{urn:1C.ru:commerceml_2}Цена" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
 *                             &lt;element name="Склад" type="{urn:1C.ru:commerceml_2}ОстаткиПоСкладам" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Подписанты" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Подписант" type="{urn:1C.ru:commerceml_2}Подписант" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="СодержитТолькоИзменения" type="{urn:1C.ru:commerceml_2}ПереключательТип" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u041f\u0430\u043a\u0435\u0442\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0439", propOrder = {
    "\u0438\u0434",
    "\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435",
    "\u0438\u0434\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0430",
    "\u0438\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430",
    "\u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0421",
    "\u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0414\u043e",
    "\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435",
    "\u0432\u043b\u0430\u0434\u0435\u043b\u0435\u0446",
    "\u0442\u0438\u043f\u044b\u0426\u0435\u043d",
    "\u0441\u043a\u043b\u0430\u0434\u044b",
    "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0421\u0432\u043e\u0439\u0441\u0442\u0432",
    "\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f",
    "\u043f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u044b"
})
public class ПакетПредложений {

    @XmlElement(name = "\u0418\u0434")
    protected String ид;
    @XmlElement(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", required = true)
    protected String наименование;
    @XmlElement(name = "\u0418\u0434\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0430", required = true)
    protected String идКаталога;
    @XmlElement(name = "\u0418\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430")
    protected String идКлассификатора;
    @XmlElement(name = "\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0421")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar действительноС;
    @XmlElement(name = "\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0414\u043e")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar действительноДо;
    @XmlElement(name = "\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435")
    protected String описание;
    @XmlElement(name = "\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446", required = true)
    protected Контрагент владелец;
    @XmlElement(name = "\u0422\u0438\u043f\u044b\u0426\u0435\u043d", required = true)
    protected ПакетПредложений.ТипыЦен типыЦен;
    @XmlElement(name = "\u0421\u043a\u043b\u0430\u0434\u044b")
    protected ПакетПредложений.Склады склады;
    @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0421\u0432\u043e\u0439\u0441\u0442\u0432")
    protected ПакетПредложений.ЗначенияСвойств значенияСвойств;
    @XmlElement(name = "\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f", required = true)
    protected ПакетПредложений.Предложения предложения;
    @XmlElement(name = "\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u044b")
    protected ПакетПредложений.Подписанты подписанты;
    @XmlAttribute(name = "\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u0442\u0422\u043e\u043b\u044c\u043a\u043e\u0418\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f")
    protected Boolean содержитТолькоИзменения;

    /**
     * Gets the value of the ид property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИд() {
        return ид;
    }

    /**
     * Sets the value of the ид property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИд(String value) {
        this.ид = value;
    }

    /**
     * Gets the value of the наименование property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНаименование() {
        return наименование;
    }

    /**
     * Sets the value of the наименование property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНаименование(String value) {
        this.наименование = value;
    }

    /**
     * Gets the value of the идКаталога property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдКаталога() {
        return идКаталога;
    }

    /**
     * Sets the value of the идКаталога property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдКаталога(String value) {
        this.идКаталога = value;
    }

    /**
     * Gets the value of the идКлассификатора property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдКлассификатора() {
        return идКлассификатора;
    }

    /**
     * Sets the value of the идКлассификатора property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдКлассификатора(String value) {
        this.идКлассификатора = value;
    }

    /**
     * Gets the value of the действительноС property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДействительноС() {
        return действительноС;
    }

    /**
     * Sets the value of the действительноС property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДействительноС(XMLGregorianCalendar value) {
        this.действительноС = value;
    }

    /**
     * Gets the value of the действительноДо property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДействительноДо() {
        return действительноДо;
    }

    /**
     * Sets the value of the действительноДо property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДействительноДо(XMLGregorianCalendar value) {
        this.действительноДо = value;
    }

    /**
     * Gets the value of the описание property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОписание() {
        return описание;
    }

    /**
     * Sets the value of the описание property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОписание(String value) {
        this.описание = value;
    }

    /**
     * Gets the value of the владелец property.
     * 
     * @return
     *     possible object is
     *     {@link Контрагент }
     *     
     */
    public Контрагент getВладелец() {
        return владелец;
    }

    /**
     * Sets the value of the владелец property.
     * 
     * @param value
     *     allowed object is
     *     {@link Контрагент }
     *     
     */
    public void setВладелец(Контрагент value) {
        this.владелец = value;
    }

    /**
     * Gets the value of the типыЦен property.
     * 
     * @return
     *     possible object is
     *     {@link ПакетПредложений.ТипыЦен }
     *     
     */
    public ПакетПредложений.ТипыЦен getТипыЦен() {
        return типыЦен;
    }

    /**
     * Sets the value of the типыЦен property.
     * 
     * @param value
     *     allowed object is
     *     {@link ПакетПредложений.ТипыЦен }
     *     
     */
    public void setТипыЦен(ПакетПредложений.ТипыЦен value) {
        this.типыЦен = value;
    }

    /**
     * Gets the value of the склады property.
     * 
     * @return
     *     possible object is
     *     {@link ПакетПредложений.Склады }
     *     
     */
    public ПакетПредложений.Склады getСклады() {
        return склады;
    }

    /**
     * Sets the value of the склады property.
     * 
     * @param value
     *     allowed object is
     *     {@link ПакетПредложений.Склады }
     *     
     */
    public void setСклады(ПакетПредложений.Склады value) {
        this.склады = value;
    }

    /**
     * Gets the value of the значенияСвойств property.
     * 
     * @return
     *     possible object is
     *     {@link ПакетПредложений.ЗначенияСвойств }
     *     
     */
    public ПакетПредложений.ЗначенияСвойств getЗначенияСвойств() {
        return значенияСвойств;
    }

    /**
     * Sets the value of the значенияСвойств property.
     * 
     * @param value
     *     allowed object is
     *     {@link ПакетПредложений.ЗначенияСвойств }
     *     
     */
    public void setЗначенияСвойств(ПакетПредложений.ЗначенияСвойств value) {
        this.значенияСвойств = value;
    }

    /**
     * Gets the value of the предложения property.
     * 
     * @return
     *     possible object is
     *     {@link ПакетПредложений.Предложения }
     *     
     */
    public ПакетПредложений.Предложения getПредложения() {
        return предложения;
    }

    /**
     * Sets the value of the предложения property.
     * 
     * @param value
     *     allowed object is
     *     {@link ПакетПредложений.Предложения }
     *     
     */
    public void setПредложения(ПакетПредложений.Предложения value) {
        this.предложения = value;
    }

    /**
     * Gets the value of the подписанты property.
     * 
     * @return
     *     possible object is
     *     {@link ПакетПредложений.Подписанты }
     *     
     */
    public ПакетПредложений.Подписанты getПодписанты() {
        return подписанты;
    }

    /**
     * Sets the value of the подписанты property.
     * 
     * @param value
     *     allowed object is
     *     {@link ПакетПредложений.Подписанты }
     *     
     */
    public void setПодписанты(ПакетПредложений.Подписанты value) {
        this.подписанты = value;
    }

    /**
     * Gets the value of the содержитТолькоИзменения property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isСодержитТолькоИзменения() {
        return содержитТолькоИзменения;
    }

    /**
     * Sets the value of the содержитТолькоИзменения property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setСодержитТолькоИзменения(Boolean value) {
        this.содержитТолькоИзменения = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ЗначенияСвойства" type="{urn:1C.ru:commerceml_2}ЗначенияСвойства" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430"
    })
    public static class ЗначенияСвойств {

        @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430", required = true)
        protected List<ЗначенияСвойства> значенияСвойства;

        /**
         * Gets the value of the значенияСвойства property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the значенияСвойства property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getЗначенияСвойства().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ЗначенияСвойства }
         * 
         * 
         */
        public List<ЗначенияСвойства> getЗначенияСвойства() {
            if (значенияСвойства == null) {
                значенияСвойства = new ArrayList<ЗначенияСвойства>();
            }
            return this.значенияСвойства;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Подписант" type="{urn:1C.ru:commerceml_2}Подписант" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442"
    })
    public static class Подписанты {

        @XmlElement(name = "\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442", required = true)
        protected List<Подписант> подписант;

        /**
         * Gets the value of the подписант property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the подписант property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getПодписант().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Подписант }
         * 
         * 
         */
        public List<Подписант> getПодписант() {
            if (подписант == null) {
                подписант = new ArrayList<Подписант>();
            }
            return this.подписант;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Предложение" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
     *                 &lt;sequence>
     *                   &lt;element name="Цены">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Цена" type="{urn:1C.ru:commerceml_2}Цена" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
     *                   &lt;element name="Склад" type="{urn:1C.ru:commerceml_2}ОстаткиПоСкладам" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435"
    })
    public static class Предложения {

        @XmlElement(name = "\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435", required = true)
        protected List<ПакетПредложений.Предложения.Предложение> предложение;

        /**
         * Gets the value of the предложение property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the предложение property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getПредложение().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ПакетПредложений.Предложения.Предложение }
         * 
         * 
         */
        public List<ПакетПредложений.Предложения.Предложение> getПредложение() {
            if (предложение == null) {
                предложение = new ArrayList<ПакетПредложений.Предложения.Предложение>();
            }
            return this.предложение;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
         *       &lt;sequence>
         *         &lt;element name="Цены">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Цена" type="{urn:1C.ru:commerceml_2}Цена" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип" minOccurs="0"/>
         *         &lt;element name="Склад" type="{urn:1C.ru:commerceml_2}ОстаткиПоСкладам" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "\u0446\u0435\u043d\u044b",
            "\u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e",
            "\u0441\u043a\u043b\u0430\u0434"
        })
        public static class Предложение
            extends Товар
        {

            @XmlElement(name = "\u0426\u0435\u043d\u044b", required = true)
            protected ПакетПредложений.Предложения.Предложение.Цены цены;
            @XmlElement(name = "\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e")
            protected BigDecimal количество;
            @XmlElement(name = "\u0421\u043a\u043b\u0430\u0434")
            protected List<ОстаткиПоСкладам> склад;

            /**
             * Gets the value of the цены property.
             * 
             * @return
             *     possible object is
             *     {@link ПакетПредложений.Предложения.Предложение.Цены }
             *     
             */
            public ПакетПредложений.Предложения.Предложение.Цены getЦены() {
                return цены;
            }

            /**
             * Sets the value of the цены property.
             * 
             * @param value
             *     allowed object is
             *     {@link ПакетПредложений.Предложения.Предложение.Цены }
             *     
             */
            public void setЦены(ПакетПредложений.Предложения.Предложение.Цены value) {
                this.цены = value;
            }

            /**
             * Gets the value of the количество property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getКоличество() {
                return количество;
            }

            /**
             * Sets the value of the количество property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setКоличество(BigDecimal value) {
                this.количество = value;
            }

            /**
             * Gets the value of the склад property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the склад property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getСклад().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ОстаткиПоСкладам }
             * 
             * 
             */
            public List<ОстаткиПоСкладам> getСклад() {
                if (склад == null) {
                    склад = new ArrayList<ОстаткиПоСкладам>();
                }
                return this.склад;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Цена" type="{urn:1C.ru:commerceml_2}Цена" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "\u0446\u0435\u043d\u0430"
            })
            public static class Цены {

                @XmlElement(name = "\u0426\u0435\u043d\u0430", required = true)
                protected List<Цена> цена;

                /**
                 * Gets the value of the цена property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the цена property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getЦена().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Цена }
                 * 
                 * 
                 */
                public List<Цена> getЦена() {
                    if (цена == null) {
                        цена = new ArrayList<Цена>();
                    }
                    return this.цена;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Склад" type="{urn:1C.ru:commerceml_2}Склад" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0441\u043a\u043b\u0430\u0434"
    })
    public static class Склады {

        @XmlElement(name = "\u0421\u043a\u043b\u0430\u0434", required = true)
        protected List<Склад> склад;

        /**
         * Gets the value of the склад property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the склад property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getСклад().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Склад }
         * 
         * 
         */
        public List<Склад> getСклад() {
            if (склад == null) {
                склад = new ArrayList<Склад>();
            }
            return this.склад;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
     *         &lt;element name="ТипЦены" type="{urn:1C.ru:commerceml_2}ТипЦены" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0438\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430",
        "\u0442\u0438\u043f\u0426\u0435\u043d\u044b"
    })
    public static class ТипыЦен {

        @XmlElement(name = "\u0418\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430")
        protected String идКлассификатора;
        @XmlElement(name = "\u0422\u0438\u043f\u0426\u0435\u043d\u044b", required = true)
        protected List<ТипЦены> типЦены;

        /**
         * Gets the value of the идКлассификатора property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getИдКлассификатора() {
            return идКлассификатора;
        }

        /**
         * Sets the value of the идКлассификатора property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setИдКлассификатора(String value) {
            this.идКлассификатора = value;
        }

        /**
         * Gets the value of the типЦены property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the типЦены property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getТипЦены().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ТипЦены }
         * 
         * 
         */
        public List<ТипЦены> getТипЦены() {
            if (типЦены == null) {
                типЦены = new ArrayList<ТипЦены>();
            }
            return this.типЦены;
        }

    }

}
