//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ПолТип.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ПолТип">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="255"/>
 *     &lt;enumeration value="М"/>
 *     &lt;enumeration value="Ж"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "\u041f\u043e\u043b\u0422\u0438\u043f")
@XmlEnum
public enum ПолТип {

    М,
    Ж;

    public String value() {
        return name();
    }

    public static ПолТип fromValue(String v) {
        return valueOf(v);
    }

}
