//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Представитель complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Представитель">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ид" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *         &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}НаименованиеТип" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;group ref="{urn:1C.ru:commerceml_2}РеквизитыЮрЛица"/>
 *           &lt;group ref="{urn:1C.ru:commerceml_2}РеквизитыФизЛица"/>
 *         &lt;/choice>
 *         &lt;element name="Комментарий" type="{urn:1C.ru:commerceml_2}КомментарийТип" minOccurs="0"/>
 *         &lt;element name="Адрес" type="{urn:1C.ru:commerceml_2}Адрес" minOccurs="0"/>
 *         &lt;element name="Контакты" type="{urn:1C.ru:commerceml_2}КонтактнаяИнформация" minOccurs="0"/>
 *         &lt;element name="Отношение" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u041f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c", propOrder = {
    "content"
})
public class Представитель {

    @XmlElementRefs({
        @XmlElementRef(name = "\u041f\u043e\u043b", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0418\u041d\u041d", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0435", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u041a\u041f\u041e", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u0444\u0438\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0435\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u041a\u0414\u041f", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439\u0412\u0438\u0434\u0414\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0420\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0435\u0421\u0447\u0435\u0442\u0430", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0418\u043c\u044f", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0415\u0413\u0420\u041f\u041e", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0418\u0434", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u041a\u041e\u041f\u0424", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041c\u0435\u0441\u0442\u043e\u0420\u043e\u0436\u0434\u0435\u043d\u0438\u044f", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439\u0410\u0434\u0440\u0435\u0441", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0414\u0430\u0442\u0430\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u041a\u0412\u042d\u0414", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041f\u043e\u043b\u043d\u043e\u0435\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0423\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u0435\u043d\u0438\u0435\u041b\u0438\u0447\u043d\u043e\u0441\u0442\u0438", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041a\u041f\u041f", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u041a\u0424\u0421", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0424\u0430\u043c\u0438\u043b\u0438\u044f", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0414\u0430\u0442\u0430\u0420\u043e\u0436\u0434\u0435\u043d\u0438\u044f", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0410\u0434\u0440\u0435\u0441\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u041e\u0442\u043d\u043e\u0448\u0435\u043d\u0438\u0435", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "\u0410\u0434\u0440\u0435\u0441", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "ИНН" is used by two different parts of a schema. See: 
     * line 1698 of file:/C:/Users/kavi/Documents/commercem2.xsd
     * line 1741 of file:/C:/Users/kavi/Documents/commercem2.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ПолТип }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link КонтактнаяИнформация }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Представитель.Организация }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link com.pirc.commerc.Подписант.МестоРаботы.РасчетныеСчета }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Адрес }{@code >}
     * {@link JAXBElement }{@code <}{@link Адрес }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Представитель.УдостоверениеЛичности }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Руководитель }{@code >}
     * {@link JAXBElement }{@code <}{@link Адрес }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Адрес }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{urn:1C.ru:commerceml_2}РеквизитыЮрЛица"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043e\u0444\u0438\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0435\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435",
        "\u044e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439\u0410\u0434\u0440\u0435\u0441",
        "\u0438\u043d\u043d",
        "\u043a\u043f\u043f",
        "\u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0439\u0412\u0438\u0434\u0414\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438",
        "\u0435\u0433\u0440\u043f\u043e",
        "\u043e\u043a\u0432\u044d\u0434",
        "\u043e\u043a\u0434\u043f",
        "\u043e\u043a\u043e\u043f\u0444",
        "\u043e\u043a\u0444\u0441",
        "\u043e\u043a\u043f\u043e",
        "\u0434\u0430\u0442\u0430\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438",
        "\u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c",
        "\u0440\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0435\u0421\u0447\u0435\u0442\u0430"
    })
    public static class Организация {

        @XmlElement(name = "\u041e\u0444\u0438\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0435\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", required = true)
        protected String официальноеНаименование;
        @XmlElement(name = "\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439\u0410\u0434\u0440\u0435\u0441")
        protected Адрес юридическийАдрес;
        @XmlElement(name = "\u0418\u041d\u041d")
        protected String инн;
        @XmlElement(name = "\u041a\u041f\u041f")
        protected String кпп;
        @XmlElement(name = "\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439\u0412\u0438\u0434\u0414\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438")
        protected String основнойВидДеятельности;
        @XmlElement(name = "\u0415\u0413\u0420\u041f\u041e")
        protected String егрпо;
        @XmlElement(name = "\u041e\u041a\u0412\u042d\u0414")
        protected String оквэд;
        @XmlElement(name = "\u041e\u041a\u0414\u041f")
        protected String окдп;
        @XmlElement(name = "\u041e\u041a\u041e\u041f\u0424")
        protected String окопф;
        @XmlElement(name = "\u041e\u041a\u0424\u0421")
        protected String окфс;
        @XmlElement(name = "\u041e\u041a\u041f\u041e")
        protected String окпо;
        @XmlElement(name = "\u0414\u0430\u0442\u0430\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar датаРегистрации;
        @XmlElement(name = "\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c")
        protected Руководитель руководитель;
        @XmlElement(name = "\u0420\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0435\u0421\u0447\u0435\u0442\u0430")
        protected com.pirc.commerc.Подписант.МестоРаботы.РасчетныеСчета расчетныеСчета;

        /**
         * Gets the value of the официальноеНаименование property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getОфициальноеНаименование() {
            return официальноеНаименование;
        }

        /**
         * Sets the value of the официальноеНаименование property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setОфициальноеНаименование(String value) {
            this.официальноеНаименование = value;
        }

        /**
         * Gets the value of the юридическийАдрес property.
         * 
         * @return
         *     possible object is
         *     {@link Адрес }
         *     
         */
        public Адрес getЮридическийАдрес() {
            return юридическийАдрес;
        }

        /**
         * Sets the value of the юридическийАдрес property.
         * 
         * @param value
         *     allowed object is
         *     {@link Адрес }
         *     
         */
        public void setЮридическийАдрес(Адрес value) {
            this.юридическийАдрес = value;
        }

        /**
         * Gets the value of the инн property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getИНН() {
            return инн;
        }

        /**
         * Sets the value of the инн property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setИНН(String value) {
            this.инн = value;
        }

        /**
         * Gets the value of the кпп property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getКПП() {
            return кпп;
        }

        /**
         * Sets the value of the кпп property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setКПП(String value) {
            this.кпп = value;
        }

        /**
         * Gets the value of the основнойВидДеятельности property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getОсновнойВидДеятельности() {
            return основнойВидДеятельности;
        }

        /**
         * Sets the value of the основнойВидДеятельности property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setОсновнойВидДеятельности(String value) {
            this.основнойВидДеятельности = value;
        }

        /**
         * Gets the value of the егрпо property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getЕГРПО() {
            return егрпо;
        }

        /**
         * Sets the value of the егрпо property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setЕГРПО(String value) {
            this.егрпо = value;
        }

        /**
         * Gets the value of the оквэд property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getОКВЭД() {
            return оквэд;
        }

        /**
         * Sets the value of the оквэд property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setОКВЭД(String value) {
            this.оквэд = value;
        }

        /**
         * Gets the value of the окдп property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getОКДП() {
            return окдп;
        }

        /**
         * Sets the value of the окдп property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setОКДП(String value) {
            this.окдп = value;
        }

        /**
         * Gets the value of the окопф property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getОКОПФ() {
            return окопф;
        }

        /**
         * Sets the value of the окопф property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setОКОПФ(String value) {
            this.окопф = value;
        }

        /**
         * Gets the value of the окфс property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getОКФС() {
            return окфс;
        }

        /**
         * Sets the value of the окфс property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setОКФС(String value) {
            this.окфс = value;
        }

        /**
         * Gets the value of the окпо property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getОКПО() {
            return окпо;
        }

        /**
         * Sets the value of the окпо property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setОКПО(String value) {
            this.окпо = value;
        }

        /**
         * Gets the value of the датаРегистрации property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getДатаРегистрации() {
            return датаРегистрации;
        }

        /**
         * Sets the value of the датаРегистрации property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setДатаРегистрации(XMLGregorianCalendar value) {
            this.датаРегистрации = value;
        }

        /**
         * Gets the value of the руководитель property.
         * 
         * @return
         *     possible object is
         *     {@link Руководитель }
         *     
         */
        public Руководитель getРуководитель() {
            return руководитель;
        }

        /**
         * Sets the value of the руководитель property.
         * 
         * @param value
         *     allowed object is
         *     {@link Руководитель }
         *     
         */
        public void setРуководитель(Руководитель value) {
            this.руководитель = value;
        }

        /**
         * Gets the value of the расчетныеСчета property.
         * 
         * @return
         *     possible object is
         *     {@link com.pirc.commerc.Подписант.МестоРаботы.РасчетныеСчета }
         *     
         */
        public com.pirc.commerc.Подписант.МестоРаботы.РасчетныеСчета getРасчетныеСчета() {
            return расчетныеСчета;
        }

        /**
         * Sets the value of the расчетныеСчета property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.pirc.commerc.Подписант.МестоРаботы.РасчетныеСчета }
         *     
         */
        public void setРасчетныеСчета(com.pirc.commerc.Подписант.МестоРаботы.РасчетныеСчета value) {
            this.расчетныеСчета = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{urn:1C.ru:commerceml_2}УдостоверениеЛичности"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0432\u0438\u0434\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430",
        "\u0441\u0435\u0440\u0438\u044f",
        "\u043d\u043e\u043c\u0435\u0440",
        "\u0434\u0430\u0442\u0430\u0412\u044b\u0434\u0430\u0447\u0438",
        "\u043a\u0435\u043c\u0412\u044b\u0434\u0430\u043d"
    })
    public static class УдостоверениеЛичности {

        @XmlElement(name = "\u0412\u0438\u0434\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430", required = true)
        protected String видДокумента;
        @XmlElement(name = "\u0421\u0435\u0440\u0438\u044f")
        protected String серия;
        @XmlElement(name = "\u041d\u043e\u043c\u0435\u0440", required = true)
        protected String номер;
        @XmlElement(name = "\u0414\u0430\u0442\u0430\u0412\u044b\u0434\u0430\u0447\u0438", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar датаВыдачи;
        @XmlElement(name = "\u041a\u0435\u043c\u0412\u044b\u0434\u0430\u043d", required = true)
        protected String кемВыдан;

        /**
         * Gets the value of the видДокумента property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getВидДокумента() {
            return видДокумента;
        }

        /**
         * Sets the value of the видДокумента property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setВидДокумента(String value) {
            this.видДокумента = value;
        }

        /**
         * Gets the value of the серия property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getСерия() {
            return серия;
        }

        /**
         * Sets the value of the серия property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setСерия(String value) {
            this.серия = value;
        }

        /**
         * Gets the value of the номер property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getНомер() {
            return номер;
        }

        /**
         * Sets the value of the номер property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setНомер(String value) {
            this.номер = value;
        }

        /**
         * Gets the value of the датаВыдачи property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getДатаВыдачи() {
            return датаВыдачи;
        }

        /**
         * Sets the value of the датаВыдачи property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setДатаВыдачи(XMLGregorianCalendar value) {
            this.датаВыдачи = value;
        }

        /**
         * Gets the value of the кемВыдан property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getКемВыдан() {
            return кемВыдан;
        }

        /**
         * Sets the value of the кемВыдан property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setКемВыдан(String value) {
            this.кемВыдан = value;
        }

    }

}
