//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Руководитель complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Руководитель">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Фамилия" type="{urn:1C.ru:commerceml_2}СтрокаТип"/>
 *         &lt;element name="Имя" type="{urn:1C.ru:commerceml_2}СтрокаТип"/>
 *         &lt;element name="Отчество" type="{urn:1C.ru:commerceml_2}СтрокаТип" minOccurs="0"/>
 *         &lt;element name="УдостоверениеЛичности" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{urn:1C.ru:commerceml_2}УдостоверениеЛичности"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="АресРегистрации" type="{urn:1C.ru:commerceml_2}Адрес" minOccurs="0"/>
 *         &lt;element name="Должность" type="{urn:1C.ru:commerceml_2}СтрокаТип"/>
 *         &lt;element name="Контакты" type="{urn:1C.ru:commerceml_2}КонтактнаяИнформация" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c", propOrder = {
    "\u0444\u0430\u043c\u0438\u043b\u0438\u044f",
    "\u0438\u043c\u044f",
    "\u043e\u0442\u0447\u0435\u0441\u0442\u0432\u043e",
    "\u0443\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u0435\u043d\u0438\u0435\u041b\u0438\u0447\u043d\u043e\u0441\u0442\u0438",
    "\u0430\u0440\u0435\u0441\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438",
    "\u0434\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c",
    "\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u044b"
})
public class Руководитель {

    @XmlElement(name = "\u0424\u0430\u043c\u0438\u043b\u0438\u044f", required = true)
    protected String фамилия;
    @XmlElement(name = "\u0418\u043c\u044f", required = true)
    protected String имя;
    @XmlElement(name = "\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e")
    protected String отчество;
    @XmlElement(name = "\u0423\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u0435\u043d\u0438\u0435\u041b\u0438\u0447\u043d\u043e\u0441\u0442\u0438")
    protected Руководитель.УдостоверениеЛичности удостоверениеЛичности;
    @XmlElement(name = "\u0410\u0440\u0435\u0441\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438")
    protected Адрес аресРегистрации;
    @XmlElement(name = "\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c", required = true)
    protected String должность;
    @XmlElement(name = "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b")
    protected КонтактнаяИнформация контакты;

    /**
     * Gets the value of the фамилия property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getФамилия() {
        return фамилия;
    }

    /**
     * Sets the value of the фамилия property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setФамилия(String value) {
        this.фамилия = value;
    }

    /**
     * Gets the value of the имя property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИмя() {
        return имя;
    }

    /**
     * Sets the value of the имя property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИмя(String value) {
        this.имя = value;
    }

    /**
     * Gets the value of the отчество property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОтчество() {
        return отчество;
    }

    /**
     * Sets the value of the отчество property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОтчество(String value) {
        this.отчество = value;
    }

    /**
     * Gets the value of the удостоверениеЛичности property.
     * 
     * @return
     *     possible object is
     *     {@link Руководитель.УдостоверениеЛичности }
     *     
     */
    public Руководитель.УдостоверениеЛичности getУдостоверениеЛичности() {
        return удостоверениеЛичности;
    }

    /**
     * Sets the value of the удостоверениеЛичности property.
     * 
     * @param value
     *     allowed object is
     *     {@link Руководитель.УдостоверениеЛичности }
     *     
     */
    public void setУдостоверениеЛичности(Руководитель.УдостоверениеЛичности value) {
        this.удостоверениеЛичности = value;
    }

    /**
     * Gets the value of the аресРегистрации property.
     * 
     * @return
     *     possible object is
     *     {@link Адрес }
     *     
     */
    public Адрес getАресРегистрации() {
        return аресРегистрации;
    }

    /**
     * Sets the value of the аресРегистрации property.
     * 
     * @param value
     *     allowed object is
     *     {@link Адрес }
     *     
     */
    public void setАресРегистрации(Адрес value) {
        this.аресРегистрации = value;
    }

    /**
     * Gets the value of the должность property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getДолжность() {
        return должность;
    }

    /**
     * Sets the value of the должность property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setДолжность(String value) {
        this.должность = value;
    }

    /**
     * Gets the value of the контакты property.
     * 
     * @return
     *     possible object is
     *     {@link КонтактнаяИнформация }
     *     
     */
    public КонтактнаяИнформация getКонтакты() {
        return контакты;
    }

    /**
     * Sets the value of the контакты property.
     * 
     * @param value
     *     allowed object is
     *     {@link КонтактнаяИнформация }
     *     
     */
    public void setКонтакты(КонтактнаяИнформация value) {
        this.контакты = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{urn:1C.ru:commerceml_2}УдостоверениеЛичности"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0432\u0438\u0434\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430",
        "\u0441\u0435\u0440\u0438\u044f",
        "\u043d\u043e\u043c\u0435\u0440",
        "\u0434\u0430\u0442\u0430\u0412\u044b\u0434\u0430\u0447\u0438",
        "\u043a\u0435\u043c\u0412\u044b\u0434\u0430\u043d"
    })
    public static class УдостоверениеЛичности {

        @XmlElement(name = "\u0412\u0438\u0434\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430", required = true)
        protected String видДокумента;
        @XmlElement(name = "\u0421\u0435\u0440\u0438\u044f")
        protected String серия;
        @XmlElement(name = "\u041d\u043e\u043c\u0435\u0440", required = true)
        protected String номер;
        @XmlElement(name = "\u0414\u0430\u0442\u0430\u0412\u044b\u0434\u0430\u0447\u0438", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar датаВыдачи;
        @XmlElement(name = "\u041a\u0435\u043c\u0412\u044b\u0434\u0430\u043d", required = true)
        protected String кемВыдан;

        /**
         * Gets the value of the видДокумента property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getВидДокумента() {
            return видДокумента;
        }

        /**
         * Sets the value of the видДокумента property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setВидДокумента(String value) {
            this.видДокумента = value;
        }

        /**
         * Gets the value of the серия property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getСерия() {
            return серия;
        }

        /**
         * Sets the value of the серия property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setСерия(String value) {
            this.серия = value;
        }

        /**
         * Gets the value of the номер property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getНомер() {
            return номер;
        }

        /**
         * Sets the value of the номер property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setНомер(String value) {
            this.номер = value;
        }

        /**
         * Gets the value of the датаВыдачи property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getДатаВыдачи() {
            return датаВыдачи;
        }

        /**
         * Sets the value of the датаВыдачи property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setДатаВыдачи(XMLGregorianCalendar value) {
            this.датаВыдачи = value;
        }

        /**
         * Gets the value of the кемВыдан property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getКемВыдан() {
            return кемВыдан;
        }

        /**
         * Sets the value of the кемВыдан property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setКемВыдан(String value) {
            this.кемВыдан = value;
        }

    }

}
