//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for СтатусТип.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="СтатусТип">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Новый"/>
 *     &lt;enumeration value="Изменен"/>
 *     &lt;enumeration value="Удален"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "\u0421\u0442\u0430\u0442\u0443\u0441\u0422\u0438\u043f")
@XmlEnum
public enum СтатусТип {

    @XmlEnumValue("\u041d\u043e\u0432\u044b\u0439")
    НОВЫЙ("\u041d\u043e\u0432\u044b\u0439"),
    @XmlEnumValue("\u0418\u0437\u043c\u0435\u043d\u0435\u043d")
    ИЗМЕНЕН("\u0418\u0437\u043c\u0435\u043d\u0435\u043d"),
    @XmlEnumValue("\u0423\u0434\u0430\u043b\u0435\u043d")
    УДАЛЕН("\u0423\u0434\u0430\u043b\u0435\u043d");
    private final String value;

    СтатусТип(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static СтатусТип fromValue(String v) {
        for (СтатусТип c: СтатусТип.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
