//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ТипЗначенийТип.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ТипЗначенийТип">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Строка"/>
 *     &lt;enumeration value="Число"/>
 *     &lt;enumeration value="Время"/>
 *     &lt;enumeration value="Справочник"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "\u0422\u0438\u043f\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0439\u0422\u0438\u043f")
@XmlEnum
public enum ТипЗначенийТип {

    @XmlEnumValue("\u0421\u0442\u0440\u043e\u043a\u0430")
    СТРОКА("\u0421\u0442\u0440\u043e\u043a\u0430"),
    @XmlEnumValue("\u0427\u0438\u0441\u043b\u043e")
    ЧИСЛО("\u0427\u0438\u0441\u043b\u043e"),
    @XmlEnumValue("\u0412\u0440\u0435\u043c\u044f")
    ВРЕМЯ("\u0412\u0440\u0435\u043c\u044f"),
    @XmlEnumValue("\u0421\u043f\u0440\u0430\u0432\u043e\u0447\u043d\u0438\u043a")
    СПРАВОЧНИК("\u0421\u043f\u0440\u0430\u0432\u043e\u0447\u043d\u0438\u043a");
    private final String value;

    ТипЗначенийТип(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ТипЗначенийТип fromValue(String v) {
        for (ТипЗначенийТип c: ТипЗначенийТип.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
