//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Описывает идентифицированный в каталоге товар
 * 
 * <p>Java class for Товар complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Товар">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:1C.ru:commerceml_2}ИдентификаторТовара"/>
 *         &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}НаименованиеТип"/>
 *         &lt;element name="БазоваяЕдиница">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="Пересчет" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;group ref="{urn:1C.ru:commerceml_2}ЕдиницаИзмерения"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Код" type="{urn:1C.ru:commerceml_2}ЕдиницаТип" />
 *                 &lt;attribute name="НаименованиеПолное" type="{urn:1C.ru:commerceml_2}СтрокаТип" />
 *                 &lt;attribute name="МеждународноеСокращение" type="{urn:1C.ru:commerceml_2}Строка3" />
 *                 &lt;attribute name="НаименованиеКраткое" type="{urn:1C.ru:commerceml_2}СтрокаТип" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ИдТовараУКонтрагента" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *         &lt;element name="Группы" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Ид" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Описание" type="{urn:1C.ru:commerceml_2}КомментарийТип" minOccurs="0"/>
 *         &lt;element name="Картинка" type="{urn:1C.ru:commerceml_2}ИмяФайлаТип" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{urn:1C.ru:commerceml_2}Производитель" minOccurs="0"/>
 *         &lt;element name="ЗначенияСвойств" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ЗначенияСвойства" type="{urn:1C.ru:commerceml_2}ЗначенияСвойства" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="СтавкиНалогов" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="СтавкаНалога" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}СтрокаТип"/>
 *                             &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Акцизы" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Акциз" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}НаименованиеТип"/>
 *                             &lt;element name="СуммаЗаЕдиницу" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
 *                             &lt;element name="Валюта" type="{urn:1C.ru:commerceml_2}ВалютаТип"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Комплектующие" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Комплектующее" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
 *                           &lt;sequence>
 *                             &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *                             &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *                             &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Аналоги" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Аналог" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
 *                           &lt;sequence>
 *                             &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *                             &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ХарактеристикиТовара" type="{urn:1C.ru:commerceml_2}ХарактеристикиТовара" minOccurs="0"/>
 *         &lt;element name="ЗначенияРеквизитов" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ЗначениеРеквизита" type="{urn:1C.ru:commerceml_2}ЗначениеРеквизита" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Статус" type="{urn:1C.ru:commerceml_2}СтатусТип" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0422\u043e\u0432\u0430\u0440", propOrder = {
    "\u0438\u0434",
    "\u0448\u0442\u0440\u0438\u0445\u043a\u043e\u0434",
    "\u0430\u0440\u0442\u0438\u043a\u0443\u043b",
    "\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435",
    "\u0431\u0430\u0437\u043e\u0432\u0430\u044f\u0415\u0434\u0438\u043d\u0438\u0446\u0430",
    "\u0438\u0434\u0422\u043e\u0432\u0430\u0440\u0430\u0423\u041a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442\u0430",
    "\u0433\u0440\u0443\u043f\u043f\u044b",
    "\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435",
    "\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430",
    "\u0441\u0442\u0440\u0430\u043d\u0430",
    "\u0442\u043e\u0440\u0433\u043e\u0432\u0430\u044f\u041c\u0430\u0440\u043a\u0430",
    "\u0432\u043b\u0430\u0434\u0435\u043b\u0435\u0446\u0422\u043e\u0440\u0433\u043e\u0432\u043e\u0439\u041c\u0430\u0440\u043a\u0438",
    "\u0438\u0437\u0433\u043e\u0442\u043e\u0432\u0438\u0442\u0435\u043b\u044c",
    "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0421\u0432\u043e\u0439\u0441\u0442\u0432",
    "\u0441\u0442\u0430\u0432\u043a\u0438\u041d\u0430\u043b\u043e\u0433\u043e\u0432",
    "\u0430\u043a\u0446\u0438\u0437\u044b",
    "\u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0442\u0443\u044e\u0449\u0438\u0435",
    "\u0430\u043d\u0430\u043b\u043e\u0433\u0438",
    "\u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438\u0422\u043e\u0432\u0430\u0440\u0430",
    "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u043e\u0432"
})
@XmlSeeAlso({
    com.pirc.commerc.Документ.Товары.Товар.class,
    com.pirc.commerc.ПакетПредложений.Предложения.Предложение.class,
    Товар.Комплектующие.Комплектующее.class,
    Товар.Аналоги.Аналог.class,
    com.pirc.commerc.ПодчиненныйДокумент.Товары.Товар.class
})
public class Товар {

    @XmlElement(name = "\u0418\u0434")
    protected String ид;
    @XmlElement(name = "\u0428\u0442\u0440\u0438\u0445\u043a\u043e\u0434")
    protected String штрихкод;
    @XmlElement(name = "\u0410\u0440\u0442\u0438\u043a\u0443\u043b")
    protected String артикул;
    @XmlElement(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", required = true)
    protected String наименование;
    @XmlElement(name = "\u0411\u0430\u0437\u043e\u0432\u0430\u044f\u0415\u0434\u0438\u043d\u0438\u0446\u0430", required = true)
    protected Товар.БазоваяЕдиница базоваяЕдиница;
    @XmlElement(name = "\u0418\u0434\u0422\u043e\u0432\u0430\u0440\u0430\u0423\u041a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442\u0430")
    protected String идТовараУКонтрагента;
    @XmlElement(name = "\u0413\u0440\u0443\u043f\u043f\u044b")
    protected Товар.Группы группы;
    @XmlElement(name = "\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435")
    protected String описание;
    @XmlElement(name = "\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430")
    protected List<String> картинка;
    @XmlElement(name = "\u0421\u0442\u0440\u0430\u043d\u0430")
    protected String страна;
    @XmlElement(name = "\u0422\u043e\u0440\u0433\u043e\u0432\u0430\u044f\u041c\u0430\u0440\u043a\u0430")
    protected String торговаяМарка;
    @XmlElement(name = "\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446\u0422\u043e\u0440\u0433\u043e\u0432\u043e\u0439\u041c\u0430\u0440\u043a\u0438")
    protected Контрагент владелецТорговойМарки;
    @XmlElement(name = "\u0418\u0437\u0433\u043e\u0442\u043e\u0432\u0438\u0442\u0435\u043b\u044c")
    protected Контрагент изготовитель;
    @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0421\u0432\u043e\u0439\u0441\u0442\u0432")
    protected Товар.ЗначенияСвойств значенияСвойств;
    @XmlElement(name = "\u0421\u0442\u0430\u0432\u043a\u0438\u041d\u0430\u043b\u043e\u0433\u043e\u0432")
    protected Товар.СтавкиНалогов ставкиНалогов;
    @XmlElement(name = "\u0410\u043a\u0446\u0438\u0437\u044b")
    protected Товар.Акцизы акцизы;
    @XmlElement(name = "\u041a\u043e\u043c\u043f\u043b\u0435\u043a\u0442\u0443\u044e\u0449\u0438\u0435")
    protected Товар.Комплектующие комплектующие;
    @XmlElement(name = "\u0410\u043d\u0430\u043b\u043e\u0433\u0438")
    protected Товар.Аналоги аналоги;
    @XmlElement(name = "\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438\u0422\u043e\u0432\u0430\u0440\u0430")
    protected ХарактеристикиТовара характеристикиТовара;
    @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u043e\u0432")
    protected Товар.ЗначенияРеквизитов значенияРеквизитов;
    @XmlAttribute(name = "\u0421\u0442\u0430\u0442\u0443\u0441")
    protected СтатусТип статус;

    /**
     * Gets the value of the ид property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИд() {
        return ид;
    }

    /**
     * Sets the value of the ид property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИд(String value) {
        this.ид = value;
    }

    /**
     * Gets the value of the штрихкод property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getШтрихкод() {
        return штрихкод;
    }

    /**
     * Sets the value of the штрихкод property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setШтрихкод(String value) {
        this.штрихкод = value;
    }

    /**
     * Gets the value of the артикул property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getАртикул() {
        return артикул;
    }

    /**
     * Sets the value of the артикул property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setАртикул(String value) {
        this.артикул = value;
    }

    /**
     * Gets the value of the наименование property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНаименование() {
        return наименование;
    }

    /**
     * Sets the value of the наименование property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНаименование(String value) {
        this.наименование = value;
    }

    /**
     * Gets the value of the базоваяЕдиница property.
     * 
     * @return
     *     possible object is
     *     {@link Товар.БазоваяЕдиница }
     *     
     */
    public Товар.БазоваяЕдиница getБазоваяЕдиница() {
        return базоваяЕдиница;
    }

    /**
     * Sets the value of the базоваяЕдиница property.
     * 
     * @param value
     *     allowed object is
     *     {@link Товар.БазоваяЕдиница }
     *     
     */
    public void setБазоваяЕдиница(Товар.БазоваяЕдиница value) {
        this.базоваяЕдиница = value;
    }

    /**
     * Gets the value of the идТовараУКонтрагента property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдТовараУКонтрагента() {
        return идТовараУКонтрагента;
    }

    /**
     * Sets the value of the идТовараУКонтрагента property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдТовараУКонтрагента(String value) {
        this.идТовараУКонтрагента = value;
    }

    /**
     * Gets the value of the группы property.
     * 
     * @return
     *     possible object is
     *     {@link Товар.Группы }
     *     
     */
    public Товар.Группы getГруппы() {
        return группы;
    }

    /**
     * Sets the value of the группы property.
     * 
     * @param value
     *     allowed object is
     *     {@link Товар.Группы }
     *     
     */
    public void setГруппы(Товар.Группы value) {
        this.группы = value;
    }

    /**
     * Gets the value of the описание property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОписание() {
        return описание;
    }

    /**
     * Sets the value of the описание property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОписание(String value) {
        this.описание = value;
    }

    /**
     * Gets the value of the картинка property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the картинка property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getКартинка().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getКартинка() {
        if (картинка == null) {
            картинка = new ArrayList<String>();
        }
        return this.картинка;
    }

    /**
     * Gets the value of the страна property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getСтрана() {
        return страна;
    }

    /**
     * Sets the value of the страна property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setСтрана(String value) {
        this.страна = value;
    }

    /**
     * Gets the value of the торговаяМарка property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getТорговаяМарка() {
        return торговаяМарка;
    }

    /**
     * Sets the value of the торговаяМарка property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setТорговаяМарка(String value) {
        this.торговаяМарка = value;
    }

    /**
     * Gets the value of the владелецТорговойМарки property.
     * 
     * @return
     *     possible object is
     *     {@link Контрагент }
     *     
     */
    public Контрагент getВладелецТорговойМарки() {
        return владелецТорговойМарки;
    }

    /**
     * Sets the value of the владелецТорговойМарки property.
     * 
     * @param value
     *     allowed object is
     *     {@link Контрагент }
     *     
     */
    public void setВладелецТорговойМарки(Контрагент value) {
        this.владелецТорговойМарки = value;
    }

    /**
     * Gets the value of the изготовитель property.
     * 
     * @return
     *     possible object is
     *     {@link Контрагент }
     *     
     */
    public Контрагент getИзготовитель() {
        return изготовитель;
    }

    /**
     * Sets the value of the изготовитель property.
     * 
     * @param value
     *     allowed object is
     *     {@link Контрагент }
     *     
     */
    public void setИзготовитель(Контрагент value) {
        this.изготовитель = value;
    }

    /**
     * Gets the value of the значенияСвойств property.
     * 
     * @return
     *     possible object is
     *     {@link Товар.ЗначенияСвойств }
     *     
     */
    public Товар.ЗначенияСвойств getЗначенияСвойств() {
        return значенияСвойств;
    }

    /**
     * Sets the value of the значенияСвойств property.
     * 
     * @param value
     *     allowed object is
     *     {@link Товар.ЗначенияСвойств }
     *     
     */
    public void setЗначенияСвойств(Товар.ЗначенияСвойств value) {
        this.значенияСвойств = value;
    }

    /**
     * Gets the value of the ставкиНалогов property.
     * 
     * @return
     *     possible object is
     *     {@link Товар.СтавкиНалогов }
     *     
     */
    public Товар.СтавкиНалогов getСтавкиНалогов() {
        return ставкиНалогов;
    }

    /**
     * Sets the value of the ставкиНалогов property.
     * 
     * @param value
     *     allowed object is
     *     {@link Товар.СтавкиНалогов }
     *     
     */
    public void setСтавкиНалогов(Товар.СтавкиНалогов value) {
        this.ставкиНалогов = value;
    }

    /**
     * Gets the value of the акцизы property.
     * 
     * @return
     *     possible object is
     *     {@link Товар.Акцизы }
     *     
     */
    public Товар.Акцизы getАкцизы() {
        return акцизы;
    }

    /**
     * Sets the value of the акцизы property.
     * 
     * @param value
     *     allowed object is
     *     {@link Товар.Акцизы }
     *     
     */
    public void setАкцизы(Товар.Акцизы value) {
        this.акцизы = value;
    }

    /**
     * Gets the value of the комплектующие property.
     * 
     * @return
     *     possible object is
     *     {@link Товар.Комплектующие }
     *     
     */
    public Товар.Комплектующие getКомплектующие() {
        return комплектующие;
    }

    /**
     * Sets the value of the комплектующие property.
     * 
     * @param value
     *     allowed object is
     *     {@link Товар.Комплектующие }
     *     
     */
    public void setКомплектующие(Товар.Комплектующие value) {
        this.комплектующие = value;
    }

    /**
     * Gets the value of the аналоги property.
     * 
     * @return
     *     possible object is
     *     {@link Товар.Аналоги }
     *     
     */
    public Товар.Аналоги getАналоги() {
        return аналоги;
    }

    /**
     * Sets the value of the аналоги property.
     * 
     * @param value
     *     allowed object is
     *     {@link Товар.Аналоги }
     *     
     */
    public void setАналоги(Товар.Аналоги value) {
        this.аналоги = value;
    }

    /**
     * Gets the value of the характеристикиТовара property.
     * 
     * @return
     *     possible object is
     *     {@link ХарактеристикиТовара }
     *     
     */
    public ХарактеристикиТовара getХарактеристикиТовара() {
        return характеристикиТовара;
    }

    /**
     * Sets the value of the характеристикиТовара property.
     * 
     * @param value
     *     allowed object is
     *     {@link ХарактеристикиТовара }
     *     
     */
    public void setХарактеристикиТовара(ХарактеристикиТовара value) {
        this.характеристикиТовара = value;
    }

    /**
     * Gets the value of the значенияРеквизитов property.
     * 
     * @return
     *     possible object is
     *     {@link Товар.ЗначенияРеквизитов }
     *     
     */
    public Товар.ЗначенияРеквизитов getЗначенияРеквизитов() {
        return значенияРеквизитов;
    }

    /**
     * Sets the value of the значенияРеквизитов property.
     * 
     * @param value
     *     allowed object is
     *     {@link Товар.ЗначенияРеквизитов }
     *     
     */
    public void setЗначенияРеквизитов(Товар.ЗначенияРеквизитов value) {
        this.значенияРеквизитов = value;
    }

    /**
     * Gets the value of the статус property.
     * 
     * @return
     *     possible object is
     *     {@link СтатусТип }
     *     
     */
    public СтатусТип getСтатус() {
        return статус;
    }

    /**
     * Sets the value of the статус property.
     * 
     * @param value
     *     allowed object is
     *     {@link СтатусТип }
     *     
     */
    public void setСтатус(СтатусТип value) {
        this.статус = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Акциз" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}НаименованиеТип"/>
     *                   &lt;element name="СуммаЗаЕдиницу" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
     *                   &lt;element name="Валюта" type="{urn:1C.ru:commerceml_2}ВалютаТип"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0430\u043a\u0446\u0438\u0437"
    })
    public static class Акцизы {

        @XmlElement(name = "\u0410\u043a\u0446\u0438\u0437", required = true)
        protected List<Товар.Акцизы.Акциз> акциз;

        /**
         * Gets the value of the акциз property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the акциз property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getАкциз().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Товар.Акцизы.Акциз }
         * 
         * 
         */
        public List<Товар.Акцизы.Акциз> getАкциз() {
            if (акциз == null) {
                акциз = new ArrayList<Товар.Акцизы.Акциз>();
            }
            return this.акциз;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}НаименованиеТип"/>
         *         &lt;element name="СуммаЗаЕдиницу" type="{urn:1C.ru:commerceml_2}СуммаТип"/>
         *         &lt;element name="Валюта" type="{urn:1C.ru:commerceml_2}ВалютаТип"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435",
            "\u0441\u0443\u043c\u043c\u0430\u0417\u0430\u0415\u0434\u0438\u043d\u0438\u0446\u0443",
            "\u0432\u0430\u043b\u044e\u0442\u0430"
        })
        public static class Акциз {

            @XmlElement(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", required = true)
            protected String наименование;
            @XmlElement(name = "\u0421\u0443\u043c\u043c\u0430\u0417\u0430\u0415\u0434\u0438\u043d\u0438\u0446\u0443", required = true)
            protected BigDecimal суммаЗаЕдиницу;
            @XmlElement(name = "\u0412\u0430\u043b\u044e\u0442\u0430", required = true)
            protected String валюта;

            /**
             * Gets the value of the наименование property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getНаименование() {
                return наименование;
            }

            /**
             * Sets the value of the наименование property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setНаименование(String value) {
                this.наименование = value;
            }

            /**
             * Gets the value of the суммаЗаЕдиницу property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getСуммаЗаЕдиницу() {
                return суммаЗаЕдиницу;
            }

            /**
             * Sets the value of the суммаЗаЕдиницу property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setСуммаЗаЕдиницу(BigDecimal value) {
                this.суммаЗаЕдиницу = value;
            }

            /**
             * Gets the value of the валюта property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getВалюта() {
                return валюта;
            }

            /**
             * Sets the value of the валюта property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setВалюта(String value) {
                this.валюта = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Аналог" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
     *                 &lt;sequence>
     *                   &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
     *                   &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0430\u043d\u0430\u043b\u043e\u0433"
    })
    public static class Аналоги {

        @XmlElement(name = "\u0410\u043d\u0430\u043b\u043e\u0433", required = true)
        protected List<Товар.Аналоги.Аналог> аналог;

        /**
         * Gets the value of the аналог property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the аналог property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getАналог().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Товар.Аналоги.Аналог }
         * 
         * 
         */
        public List<Товар.Аналоги.Аналог> getАналог() {
            if (аналог == null) {
                аналог = new ArrayList<Товар.Аналоги.Аналог>();
            }
            return this.аналог;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
         *       &lt;sequence>
         *         &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
         *         &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "\u0438\u0434\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0430",
            "\u0438\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430"
        })
        public static class Аналог
            extends Товар
        {

            @XmlElement(name = "\u0418\u0434\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0430")
            protected String идКаталога;
            @XmlElement(name = "\u0418\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430")
            protected String идКлассификатора;

            /**
             * Gets the value of the идКаталога property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getИдКаталога() {
                return идКаталога;
            }

            /**
             * Sets the value of the идКаталога property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setИдКаталога(String value) {
                this.идКаталога = value;
            }

            /**
             * Gets the value of the идКлассификатора property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getИдКлассификатора() {
                return идКлассификатора;
            }

            /**
             * Sets the value of the идКлассификатора property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setИдКлассификатора(String value) {
                this.идКлассификатора = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="Пересчет" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;group ref="{urn:1C.ru:commerceml_2}ЕдиницаИзмерения"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Код" type="{urn:1C.ru:commerceml_2}ЕдиницаТип" />
     *       &lt;attribute name="НаименованиеПолное" type="{urn:1C.ru:commerceml_2}СтрокаТип" />
     *       &lt;attribute name="МеждународноеСокращение" type="{urn:1C.ru:commerceml_2}Строка3" />
     *       &lt;attribute name="НаименованиеКраткое" type="{urn:1C.ru:commerceml_2}СтрокаТип" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class БазоваяЕдиница {

        @XmlElementRef(name = "\u041f\u0435\u0440\u0435\u0441\u0447\u0435\u0442", namespace = "urn:1C.ru:commerceml_2", type = JAXBElement.class, required = false)
        @XmlMixed
        protected List<Serializable> content;
        @XmlAttribute(name = "\u041a\u043e\u0434")
        protected String код;
        @XmlAttribute(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435\u041f\u043e\u043b\u043d\u043e\u0435")
        protected String наименованиеПолное;
        @XmlAttribute(name = "\u041c\u0435\u0436\u0434\u0443\u043d\u0430\u0440\u043e\u0434\u043d\u043e\u0435\u0421\u043e\u043a\u0440\u0430\u0449\u0435\u043d\u0438\u0435")
        protected String международноеСокращение;
        @XmlAttribute(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435\u041a\u0440\u0430\u0442\u043a\u043e\u0435")
        protected String наименованиеКраткое;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * {@link JAXBElement }{@code <}{@link Товар.БазоваяЕдиница.Пересчет }{@code >}
         * 
         * 
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }

        /**
         * Gets the value of the код property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getКод() {
            return код;
        }

        /**
         * Sets the value of the код property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setКод(String value) {
            this.код = value;
        }

        /**
         * Gets the value of the наименованиеПолное property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getНаименованиеПолное() {
            return наименованиеПолное;
        }

        /**
         * Sets the value of the наименованиеПолное property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setНаименованиеПолное(String value) {
            this.наименованиеПолное = value;
        }

        /**
         * Gets the value of the международноеСокращение property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getМеждународноеСокращение() {
            return международноеСокращение;
        }

        /**
         * Sets the value of the международноеСокращение property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setМеждународноеСокращение(String value) {
            this.международноеСокращение = value;
        }

        /**
         * Gets the value of the наименованиеКраткое property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getНаименованиеКраткое() {
            return наименованиеКраткое;
        }

        /**
         * Sets the value of the наименованиеКраткое property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setНаименованиеКраткое(String value) {
            this.наименованиеКраткое = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;group ref="{urn:1C.ru:commerceml_2}ЕдиницаИзмерения"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "\u0435\u0434\u0438\u043d\u0438\u0446\u0430",
            "\u043a\u043e\u044d\u0444\u0444\u0438\u0446\u0438\u0435\u043d\u0442",
            "\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435\u0414\u0430\u043d\u043d\u044b\u0435"
        })
        public static class Пересчет {

            @XmlElement(name = "\u0415\u0434\u0438\u043d\u0438\u0446\u0430")
            protected String единица;
            @XmlElement(name = "\u041a\u043e\u044d\u0444\u0444\u0438\u0446\u0438\u0435\u043d\u0442")
            protected String коэффициент;
            @XmlElement(name = "\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435\u0414\u0430\u043d\u043d\u044b\u0435")
            protected com.pirc.commerc.ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные дополнительныеДанные;

            /**
             * Gets the value of the единица property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getЕдиница() {
                return единица;
            }

            /**
             * Sets the value of the единица property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setЕдиница(String value) {
                this.единица = value;
            }

            /**
             * Gets the value of the коэффициент property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getКоэффициент() {
                return коэффициент;
            }

            /**
             * Sets the value of the коэффициент property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setКоэффициент(String value) {
                this.коэффициент = value;
            }

            /**
             * Gets the value of the дополнительныеДанные property.
             * 
             * @return
             *     possible object is
             *     {@link com.pirc.commerc.ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные }
             *     
             */
            public com.pirc.commerc.ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные getДополнительныеДанные() {
                return дополнительныеДанные;
            }

            /**
             * Sets the value of the дополнительныеДанные property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.pirc.commerc.ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные }
             *     
             */
            public void setДополнительныеДанные(com.pirc.commerc.ПодчиненныйДокумент.Товары.Товар.ДополнительныеДанные value) {
                this.дополнительныеДанные = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Ид" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0438\u0434"
    })
    public static class Группы {

        @XmlElement(name = "\u0418\u0434", required = true)
        protected List<String> ид;

        /**
         * Gets the value of the ид property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ид property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getИд().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getИд() {
            if (ид == null) {
                ид = new ArrayList<String>();
            }
            return this.ид;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ЗначениеРеквизита" type="{urn:1C.ru:commerceml_2}ЗначениеРеквизита" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u0430"
    })
    public static class ЗначенияРеквизитов {

        @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u0430", required = true)
        protected List<ЗначениеРеквизита> значениеРеквизита;

        /**
         * Gets the value of the значениеРеквизита property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the значениеРеквизита property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getЗначениеРеквизита().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ЗначениеРеквизита }
         * 
         * 
         */
        public List<ЗначениеРеквизита> getЗначениеРеквизита() {
            if (значениеРеквизита == null) {
                значениеРеквизита = new ArrayList<ЗначениеРеквизита>();
            }
            return this.значениеРеквизита;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ЗначенияСвойства" type="{urn:1C.ru:commerceml_2}ЗначенияСвойства" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430"
    })
    public static class ЗначенияСвойств {

        @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430", required = true)
        protected List<ЗначенияСвойства> значенияСвойства;

        /**
         * Gets the value of the значенияСвойства property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the значенияСвойства property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getЗначенияСвойства().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ЗначенияСвойства }
         * 
         * 
         */
        public List<ЗначенияСвойства> getЗначенияСвойства() {
            if (значенияСвойства == null) {
                значенияСвойства = new ArrayList<ЗначенияСвойства>();
            }
            return this.значенияСвойства;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Комплектующее" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
     *                 &lt;sequence>
     *                   &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
     *                   &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
     *                   &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0442\u0443\u044e\u0449\u0435\u0435"
    })
    public static class Комплектующие {

        @XmlElement(name = "\u041a\u043e\u043c\u043f\u043b\u0435\u043a\u0442\u0443\u044e\u0449\u0435\u0435", required = true)
        protected List<Товар.Комплектующие.Комплектующее> комплектующее;

        /**
         * Gets the value of the комплектующее property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the комплектующее property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getКомплектующее().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Товар.Комплектующие.Комплектующее }
         * 
         * 
         */
        public List<Товар.Комплектующие.Комплектующее> getКомплектующее() {
            if (комплектующее == null) {
                комплектующее = new ArrayList<Товар.Комплектующие.Комплектующее>();
            }
            return this.комплектующее;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{urn:1C.ru:commerceml_2}Товар">
         *       &lt;sequence>
         *         &lt;element name="ИдКаталога" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
         *         &lt;element name="ИдКлассификатора" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
         *         &lt;element name="Количество" type="{urn:1C.ru:commerceml_2}КоличествоТип"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "\u0438\u0434\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0430",
            "\u0438\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430",
            "\u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e"
        })
        public static class Комплектующее
            extends Товар
        {

            @XmlElement(name = "\u0418\u0434\u041a\u0430\u0442\u0430\u043b\u043e\u0433\u0430")
            protected String идКаталога;
            @XmlElement(name = "\u0418\u0434\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u0430")
            protected String идКлассификатора;
            @XmlElement(name = "\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e", required = true)
            protected BigDecimal количество;

            /**
             * Gets the value of the идКаталога property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getИдКаталога() {
                return идКаталога;
            }

            /**
             * Sets the value of the идКаталога property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setИдКаталога(String value) {
                this.идКаталога = value;
            }

            /**
             * Gets the value of the идКлассификатора property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getИдКлассификатора() {
                return идКлассификатора;
            }

            /**
             * Sets the value of the идКлассификатора property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setИдКлассификатора(String value) {
                this.идКлассификатора = value;
            }

            /**
             * Gets the value of the количество property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getКоличество() {
                return количество;
            }

            /**
             * Sets the value of the количество property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setКоличество(BigDecimal value) {
                this.количество = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="СтавкаНалога" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}СтрокаТип"/>
     *                   &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0441\u0442\u0430\u0432\u043a\u0430\u041d\u0430\u043b\u043e\u0433\u0430"
    })
    public static class СтавкиНалогов {

        @XmlElement(name = "\u0421\u0442\u0430\u0432\u043a\u0430\u041d\u0430\u043b\u043e\u0433\u0430", required = true)
        protected List<Товар.СтавкиНалогов.СтавкаНалога> ставкаНалога;

        /**
         * Gets the value of the ставкаНалога property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ставкаНалога property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getСтавкаНалога().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Товар.СтавкиНалогов.СтавкаНалога }
         * 
         * 
         */
        public List<Товар.СтавкиНалогов.СтавкаНалога> getСтавкаНалога() {
            if (ставкаНалога == null) {
                ставкаНалога = new ArrayList<Товар.СтавкиНалогов.СтавкаНалога>();
            }
            return this.ставкаНалога;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}СтрокаТип"/>
         *         &lt;element name="Ставка" type="{urn:1C.ru:commerceml_2}КоэффициентТип"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435",
            "\u0441\u0442\u0430\u0432\u043a\u0430"
        })
        public static class СтавкаНалога {

            @XmlElement(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", required = true)
            protected String наименование;
            @XmlElement(name = "\u0421\u0442\u0430\u0432\u043a\u0430", required = true)
            protected String ставка;

            /**
             * Gets the value of the наименование property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getНаименование() {
                return наименование;
            }

            /**
             * Sets the value of the наименование property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setНаименование(String value) {
                this.наименование = value;
            }

            /**
             * Gets the value of the ставка property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getСтавка() {
                return ставка;
            }

            /**
             * Sets the value of the ставка property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setСтавка(String value) {
                this.ставка = value;
            }

        }

    }

}
