//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 07:22:14 PM MSK 
//


package com.pirc.commerc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Уточняет характеристики поставляемого товара. Товар с разными характеристиками может иметь разную цену
 * 
 * <p>Java class for ХарактеристикиТовара complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ХарактеристикиТовара">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ХарактеристикаТовара" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Ид" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
 *                   &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}НаименованиеТип"/>
 *                   &lt;element name="Значение" type="{urn:1C.ru:commerceml_2}ЗначениеТип"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438\u0422\u043e\u0432\u0430\u0440\u0430", propOrder = {
    "\u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430\u0422\u043e\u0432\u0430\u0440\u0430"
})
public class ХарактеристикиТовара {

    @XmlElement(name = "\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430\u0422\u043e\u0432\u0430\u0440\u0430", required = true)
    protected List<ХарактеристикиТовара.ХарактеристикаТовара> характеристикаТовара;

    /**
     * Gets the value of the характеристикаТовара property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the характеристикаТовара property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getХарактеристикаТовара().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ХарактеристикиТовара.ХарактеристикаТовара }
     * 
     * 
     */
    public List<ХарактеристикиТовара.ХарактеристикаТовара> getХарактеристикаТовара() {
        if (характеристикаТовара == null) {
            характеристикаТовара = new ArrayList<ХарактеристикиТовара.ХарактеристикаТовара>();
        }
        return this.характеристикаТовара;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Ид" type="{urn:1C.ru:commerceml_2}ИдентификаторГлобальныйТип" minOccurs="0"/>
     *         &lt;element name="Наименование" type="{urn:1C.ru:commerceml_2}НаименованиеТип"/>
     *         &lt;element name="Значение" type="{urn:1C.ru:commerceml_2}ЗначениеТип"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0438\u0434",
        "\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435",
        "\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435"
    })
    public static class ХарактеристикаТовара {

        @XmlElement(name = "\u0418\u0434")
        protected String ид;
        @XmlElement(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", required = true)
        protected String наименование;
        @XmlElement(name = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435", required = true)
        protected String значение;

        /**
         * Gets the value of the ид property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getИд() {
            return ид;
        }

        /**
         * Sets the value of the ид property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setИд(String value) {
            this.ид = value;
        }

        /**
         * Gets the value of the наименование property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getНаименование() {
            return наименование;
        }

        /**
         * Sets the value of the наименование property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setНаименование(String value) {
            this.наименование = value;
        }

        /**
         * Gets the value of the значение property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getЗначение() {
            return значение;
        }

        /**
         * Sets the value of the значение property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setЗначение(String value) {
            this.значение = value;
        }

    }

}
